### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by HunterOtobe** [samphonic/MoppyClassic#10]
I am trying to set this up with a single drive to start.  MoppyDesk compiles and seems to be running fine, and I have tested the connections as was shown in the video (http://www.youtube.com/watch?v=w6tuMn5sPyM) and have confirmed which pins are for step and direction and they are connected to the proper pins on my Arduino UNO.  Except that when I press the MoppyDesk play button the drive doesn't respond at all.  A little light blinks for a while on the Arduino and nothing else happens.  Console output says it has loaded a sequence with 3 MIDI channels, and the tempo has been changed to 100.  Any idea what I might be doing wrong?

**Comment by HunterOtobe** [comment]
Never mind.  I figured it out, it was a problem with uploading the arduino sketch before running MoppyDesk.  This is an awesome project, thanks for all your hard work.

**Comment by samphonic** [comment]
Hooray!  Sorry I didn't get here in time to help, but glad you got it working.
