### ISSUE TITLE
NetBeans doesn't recognize Moppy as a project

### ISSUE THREAD

**Issue by RedFox1177** [samphonic/MoppyClassic#104]
I have recently downloaded moppy, and when i went to start it, NetBeans would not find the project. Any suggestions?

Thanks,
RedFox1177

**Comment by lpulley** [comment]
NetBeans should recognize the folder Moppy-moppy-advanced/Java/MoppyDesk as a project.

In short, it's looking for a folder, not a file, to represent the project.

**Comment by samphonic** [comment]
Like @QwertzHz said, you should be able to go to File>Open and then open the MoppyDesk folder.  If that's not working, can you show a screenshot of your Open dialog when you're trying to open the project?

**Comment by RedFox1177** [comment]
I will when I get to it. Thanks for your imput!

**Comment by solidsnake745** [comment]
Closing as there has been no update to this for a while.
