### ISSUE TITLE
Moppy: could not find or load main class

### ISSUE THREAD

**Issue by Matthew0220** [samphonic/MoppyClassic#114]
Hi i need help for i don't know what's the problem :(
I get this when i trying to start the project.
I have windows 10 pro 32 bit.
![error](https://cloud.githubusercontent.com/assets/15145392/10521054/e2cccd2e-736d-11e5-82a2-97c821a0d6f9.png)

**Comment by samphonic** [comment]
Huh, interesting.  If I had to take a guess, I'd say you should right click on your project, go to properties, and make sure the main class is set to MoppyUI.java.

A quick Google for that error provides some other potential solutions, but I think it's basically having trouble finding MoppyUI to run.  You could also try right clicking on MoppyUI and choosing "Run this file" directly.

**Comment by Matthew0220** [comment]
I tried to single-run only MoppyUI.java and again i get could not get or load main class. There is the photo's...
![nevtelen](https://cloud.githubusercontent.com/assets/15145392/10558044/f25b1516-74c1-11e5-99c9-8d0c2c678151.png)

And there's the run settings...

![nevtelen1](https://cloud.githubusercontent.com/assets/15145392/10558043/e47e0160-74c1-11e5-9d44-0d7c214f2cec.png)

**Comment by tg44** [comment]
Regarding to google:
https://www.youtube.com/watch?v=2vTbonqij_Q
http://stackoverflow.com/questions/18814602/error-could-not-find-or-load-main-class-netbeans-and-java
http://stackoverflow.com/questions/20034377/netbeans-error-could-not-find-or-load-main-class

I saw you are useing hungarian windows. It could be a possible issue if your user name contains áéőúóüö characters and you working on documents or desktop.
If you write me on fb I will try to help you, in our native lang it would be much faster ;)

**Comment by solidsnake745** [comment]
To me it doesn't look like it's building the entire project. It states it's only compiling one source file, yet there are more than 20 files in the project.

Try right clicking the project and selecting "Clean and Build". After that try right clicking the project again and hitting "Run". If it's still not working, can you provide a screenshot of the Clean and Build action?

**Comment by Matthew0220** [comment]
Tg44 i writed to you on facebook.
Solidsnake i tryed what you typed and this happend.
![error1](https://cloud.githubusercontent.com/assets/15145392/10559880/5be1fefe-74fa-11e5-8b5d-7bae36e81ff6.png)
"Run"
![error2](https://cloud.githubusercontent.com/assets/15145392/10559885/6e242f42-74fa-11e5-937a-015b5ec9d020.png)

**Comment by Matthew0220** [comment]
Problem solved!!!
I downloaded java jdk8 and set to jdk8 the netbeans and deleted the vm options from properties-run.
Thx for help!

**Comment by samphonic** [comment]
Hooray!  Glad you got it solved.  The vm options might be needed to get the serial communication working, but it might not be required (depends on how your system is set up).

Thanks for sharing what you did to get it working though, that'll be helpful for others.
