### ISSUE TITLE
Drives Not Playing

### ISSUE THREAD

**Issue by doodgerdog** [samphonic/MoppyClassic#126]
I can't really explain it so here is a screen cap 
![capture](https://cloud.githubusercontent.com/assets/17696083/13561098/918531aa-e3dd-11e5-881f-ca31f021e93e.PNG)

**Comment by solidsnake745** [comment]
Looks like it couldn't find or load the main class moppydesk.MoppyUI.

Check and make sure that file is there. Resolve the error that's on that class file (has a red exclamation mark in the file browser on the left).

**Comment by doodgerdog** [comment]
So apparently I had an old version of Moppy.
But now that I have downloaded the newest version I am getting 4 errors.
![error1](https://cloud.githubusercontent.com/assets/17696083/13625641/b205d2e4-e56e-11e5-9a79-f99e6ead76b9.PNG)
![error2](https://cloud.githubusercontent.com/assets/17696083/13625643/b3a001f6-e56e-11e5-8e24-dde4ea2986be.PNG)
![error3](https://cloud.githubusercontent.com/assets/17696083/13625645/b564f816-e56e-11e5-8be4-5f0bfa77071d.PNG)
![error4](https://cloud.githubusercontent.com/assets/17696083/13625647/b6ad4674-e56e-11e5-8644-948a64b46a72.PNG)
What should I do to resolve the errors? Sorry I suck at Java.

**Comment by doodgerdog** [comment]
Also I haven't changed anything in the file so everything should be there.

**Comment by solidsnake745** [comment]
I don't know what the errors are. You should let us know what they say because they could be a wide variety of problems. But taking a wild guess, I'd say it's having trouble importing the GNU library. That library comes from the included package in the SerialDrivers folder: nrjavaserial-3.9.3.jar. Make sure under libraries you see a reference for it and then make sure that file is in the correct location.

**Comment by doodgerdog** [comment]
Alright MoppyControlWindow.java says that it contains files with errors.
And nrjavaserial-3.9.3.jar is in the serialdrivers folder but they still say "Package gnu.io does not exhist"
Should I just re-install java?

**Comment by solidsnake745** [comment]
Reinstalling either the JDK or the runtime won't resolve the issue. The library doesn't come from the Java installation. What about the reference I asked about? Is there a reference to that nrjavaserial-3.9.3 in the project (under 'Libraries')?

**Comment by doodgerdog** [comment]
nrjavaserial-3.9.3 is in Moppy-moppy-advanced\Java\SerialDrivers. But I don't see a folder in the netbeans project that is titled 'Libraries'.

**Comment by doodgerdog** [comment]
is the folder titled "lib"?

**Comment by solidsnake745** [comment]
No, it's called Libraries. 

Using your screenshot:
![image](https://cloud.githubusercontent.com/assets/1118404/13705263/12009868-e76e-11e5-85b9-be0103df8ab6.png)

**Comment by doodgerdog** [comment]
![its not there](https://cloud.githubusercontent.com/assets/17696083/13798142/891a8c5a-ead0-11e5-80c0-04d0c300647c.PNG)
Its not there

**Comment by solidsnake745** [comment]
Sorry, have not had time to look at this. Very busy at work. I'll try to look tonight.

**Comment by doodgerdog** [comment]
Alright

**Comment by doodgerdog** [comment]
Hey solid you still there?

**Comment by solidsnake745** [comment]
I somehow managed to get food poisoning the night I said I'd reply. Since then I've been trying to catch up at work since I had to take two days off. Deadlines to be met. Forgot to get back, sorry.

That looks like the problem. Add the nrjavaserial JAR as a library. Right click on libraries and then select 'Add JAR/Folder'. Once you add that you should be able to compile. This is how my Libraries looks.

![image](https://cloud.githubusercontent.com/assets/1118404/13949478/a9137eec-effb-11e5-9d34-370ca82bce08.png)

**Comment by doodgerdog** [comment]
Thanks so much! If I run into any further problems Ill be sure to ask!

**Comment by doodgerdog** [comment]
Hey sorry to bother you again. So everything works except for when I press the play button the program says it is playing but the floppy drives aren't moving or responding. Their lights aren't on either. I know its probably a hardware issue but I don't know where else to ask something like this. Thanks.

**Comment by doodgerdog** [comment]
I know that both drives are getting power as the power-supply is functioning and I just tested the plugs going to the floppy drives with my multimeter and they have power. But my drives lights still aren't on.

**Comment by doodgerdog** [comment]
I have them wired up in this configuration.
![ftvblmxh2myka1k medium](https://cloud.githubusercontent.com/assets/17696083/13974563/07132100-f06a-11e5-8c9d-fa2da4db3bd6.jpg)

**Comment by RedFox1177** [comment]
Have you put drive select B to ground?

On Tuesday, March 22, 2016, doodgerdog notifications@github.com wrote:

> Hey sorry to bother you again. So everything works except for when I press
> the play button the program says it is playing but the floppy drives aren't
> moving or responding. Their lights aren't on either. I know its probably a
> hardware issue but I don't know where else to ask something like this.
> Thanks.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/SammyIAm/Moppy/issues/126#issuecomment-200137619

## 

-Owen Vogelgesang

**Comment by doodgerdog** [comment]
No it is wired exactly like it is in the image.

**Comment by solidsnake745** [comment]
Sorry, I've been really preoccupied, did you still need help with this?

**Comment by doodgerdog** [comment]
Yes I do. Thank you.

**Comment by solidsnake745** [comment]
Where is this image from? That wiring is wrong. It shows connections to pins 20 and 22 on the floppy drive connector. The pins you need are 18 and 20. I've updated the image you've linked with the correct information. I don't have a great image editing software, but basically the step and direction pins I've pointed out need to be connected together.

![image](https://cloud.githubusercontent.com/assets/1118404/14430055/04a74d4c-ffce-11e5-9f06-df70bd4024c8.png)

**Comment by doodgerdog** [comment]
I would assume that the ground pins for 18 and 20 go to ground instead of 19 and 20.

**Comment by doodgerdog** [comment]
Yay everything is working now except uploading to my UNO. The error report says>
avrdude: ser_open(): can't open device "\\.\COM1": The system cannot find the file specified.

**Comment by doodgerdog** [comment]
I just got everything powered up, but there is just one last problem. When I try to upload moppy for arduino it gets half way done and then says;
avrdude: ser_open(): can't open device "\.\COM1": The system cannot find the file specified.

**Comment by AmEv7Fam** [comment]
Sounds like you're in the Arduino IDE to me. If so, double-check your serial port in it; almost sounds like it's trying to grab the computer's built-in serial port (COM1), which most likely isn't what your Arduino is connected to.

**Comment by doodgerdog** [comment]
So I uninstalled IDE and installed the newest version and then added the timer one library and this is what its giving me. 

> C:\Users\dodge\Desktop\Moppy\Moppy.ino:8:0: warning: "RESOLUTION" redefined [enabled by default]
> 
>  #define RESOLUTION 40 //Microsecond resolution for notes
> 
>  ^
> 
> In file included from C:\Users\dodge\Desktop\Moppy\Moppy.ino:1:0:
> 
> C:\Program Files (x86)\Arduino\libraries\Timerone/TimerOne.h:42:0: note: this is the location of the previous definition
> 
>  #define RESOLUTION 65536    // Timer1 is 16 bit
> 
>  ^
> 
> Sketch uses 3,658 bytes (11%) of program storage space. Maximum is 32,256 bytes.
> Global variables use 333 bytes (16%) of dynamic memory, leaving 1,715 bytes for local variables. Maximum is 2,048 bytes.
> avrdude: ser_open(): can't open device "\.\COM1": The system cannot find the file specified.
> 
> Problem uploading to board.  See http://www.arduino.cc/en/Guide/Troubleshooting#upload for suggestions.

**Comment by AmEv7Fam** [comment]
What options to you have for Options -> Serial port in the Arduino IDE? Try changing in them.

**Comment by doodgerdog** [comment]
There is no options tab that I can find.
And this is also a problem 
C:\Users\dodge\Desktop\Moppy\Moppy.ino:8:0: warning: "RESOLUTION" redefined [enabled by default]

 #define RESOLUTION 40 //Microsecond resolution for notes

 ^

In file included from C:\Users\dodge\Desktop\Moppy\Moppy.ino:1:0:

C:\Users\dodge\Desktop\arduino-nightly-windows\arduino-nightly\libraries\Timerone/TimerOne.h:42:0: note: this is the location of the previous definition

 #define RESOLUTION 65536    // Timer1 is 16 bit

 ^

**Comment by AmEv7Fam** [comment]
Possibly, but I'm not sure.

Is this what you're seeing?
![clipboard01](https://cloud.githubusercontent.com/assets/1711170/14591080/9d78a8b0-04c7-11e6-8b3a-6edc26ae7e11.jpg)

**Comment by samphonic** [comment]
Just to make sure things are clear:

| Arduino Pin | Floppy Pin |
| --- | --- |
| 2 | 20 |
| 3 | 18 |
| GND | 17 & 19* |

\* Or just one of them, or the ground on the power connector.  In theory all three of those should be connected, so setting any to ground should ground the rest.

The #RESOLUTION issue sounds like it might be a new bug in the Moppy code.  In the Moppy.ino file, try replacing any instance of "RESOLUTION" with "MOPPY_RESOLUTION".  (Looks like just lines 8 and 74)  It seems like in the latest nightly build of Timer (which it looks like you downloaded), that they are also defining a RESOLUTION constant that's conflicting with Moppy's

**Comment by doodgerdog** [comment]
Great they are working now! Thanks!
