### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Goemansj** [samphonic/MoppyClassic#158]
/var/folders/mf/pnw77kbs18n0crnhl7wytj380000gq/T/arduino_modified_sketch_938560/sketch_mar29a.ino:1:22: fatal error: TimerOne.h: No such file or directory
 #include <TimerOne.h>
                      ^
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Uno.

What do I do?

**Comment by MoppyDoppy** [comment]
Dowload 
https://github.com/PaulStoffregen/TimerOne (Version 1.1.0 works fine) as ZIP
Start Arduino 
goto menu Sketch|Include Library|Add ZIP Library
and choose your download.

**Comment by samphonic** [comment]
^ That should work fine.
