### ISSUE TITLE
Hard disk drives and Moppy

### ISSUE THREAD

**Issue by Goicannafr** [samphonic/MoppyClassic#160]
Hello! I'm wondering if it's necessary to modify the code on Moppy to play MIDI on HDD.
From what I understand, it's important to amplify the signal with transistors, but I can't figure out how to do it.
Any advice or help will be appreciated. Thanks!

**Comment by samphonic** [comment]
Sorry for the long gap in replying.  The signal that gets output from the "Step" pins (even numbered pins) will essentially be a square wave at the correct frequency for the MIDI note, so you shouldn't need to modify the Arduino code at all.

I don't know for sure the specifics of connecting that signal to the HDD, but it does seem likely that you'd need to use a transistor to really get much sound out of it.  You *could* try it directly from the Arduino, but I guess there's a chance you could damage the Arduino if it tries to draw too much current.
