### ISSUE TITLE
Using Moppy with Arduino Mega

### ISSUE THREAD

**Issue by vavankado** [samphonic/MoppyClassic#169]
Is-it possible to use Moppy with an Arduino Mega ? If it's yes, can you tell me how ?

**Comment by MoppyDoppy** [comment]
Yes. I think it was with no changes on the sketch. If it compiles it works. 
You must look at the hardware pinlayout to wire it. My mega was a 5v Version. If you have a 3.3v version you may need a level shifter. 
On my older videos the right side is a mega.

**Comment by samphonic** [comment]
As @MoppyDoppy says, it should just work as-is without any changes.  If you want to add more than 8 drives, you'll need to modify the Arduino sketch, but the Java code should still be good as-is as well.
