### ISSUE TITLE
option to unlock full note range?

### ISSUE THREAD

**Issue by omnislash772** [samphonic/MoppyClassic#17]
it would be cool to be able to experiment with the different notes but i have no clue what code to change for it

**Comment by samphonic** [comment]
In the top of the MoppyPlayer.java file, there is a large array of micro-second periods that correspond to their MIDI-note equivalent.  For example, a C4 is MIDI note 60, so index 60 of that array contains the period for C4.

A period of _0_ is treated as a special-case and turns the drive off (i.e. the drive doesn't play a note when you tell it to play at period 0).  As you see in the array, notes outside of the supported range are just mapped to 0, so the drives stay off for those notes.  If you'd like to try playing with additional notes, all you need to do is fill in the missing parts of the array with the appropriate period (in micro-seconds, don't forget!).
