### ISSUE TITLE
the first drive (5,25) makes music, but dont moves

### ISSUE THREAD

**Issue by FelipeZanou** [samphonic/MoppyClassic#175]
i have 2 drives conected to the arduino, the first drive (pins 2 and 3) its a 5,25 inch drive, the second drive (pins 4 and 5) its a 3,5 inch drive.
the problem is that the first drive (the 5,25 inch one) makes music but dont moves.
I checked all the wires, they are all properly conected, and i cant see fissical damage to the drive, so i dont know what is wrong, thanks.
i have a video of it:
https://drive.google.com/file/d/0B-kf5eIyr7QVVThQdUdseUR0VWM/view?usp=sharing
(pd: sorry if my english is bad)

**Comment by FelipeZanou** [comment]
i fixed it, the motor was broken

**Comment by samphonic** [comment]
Glad you got it fixed!
