### ISSUE TITLE
Serial connect issue (libNRJavaSerial.dll)

### ISSUE THREAD

**Issue by rorrexatnys** [samphonic/MoppyClassic#187]
Hey all, so I've got my 'ol floppy drives ready and compiled MoppyDesk using NetBeans "Clean and Build Main Project". Arduino is loaded with latest Moppy program and recognized on COM 3. I can run the MoppyDesk JAR, however when I click "connect" in the MoppyDesk GUI, the program closes and produces the following error:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000006c862e, pid=6236, tid=5380
#
# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.1+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.1+11, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [libNRJavaSerial.dll+0x862e]
```
More info:
I do have nrjavaserial-3.93 in my "lib" folder where the MoppyDesk JAR is.
I tried putting nrjavaserial in my JRE "lib" folder.
I also tried putting nrjavaserial in ' netbeans_jdkhome="C:\Program Files\Java\jdk-9.0.1" ' (from NetBeans conf. file).
Running Windows 10 64-bit.
I'm very novice with Java and NetBeans.

Any help is greatly appreciated!

**Comment by rorrexatnys** [comment]
Nevermind, turns out a re-installation of JDK (version 8) and NetBeans fixed it.

**Comment by samphonic** [comment]
Glad you got it fixed!
