### ISSUE TITLE
Potentially a useful tool for converting MIDIs

### ISSUE THREAD

**Issue by 1030** [samphonic/MoppyClassic#19]
Hello, this isn't really an issue but I didn't know where else to post.
http://www.midi-plugins.de/mplug/mplug-splpol.html

This is a plugin called Split Poly. From reading the site it looks like exactly what we need to convert MIDI files to Moppy compatible ones. It looks for overlapping notes and pushes them to a free channel.

I'm on a Mac so can't test it (the software is Windows only), but I thought someone out there would benefit from it.

Let me know if it works! There's a demo version that'll convert the first half of the track.

Cheers,
J

**Comment by DigitallyRemastered** [comment]
That. is. awesome! I've been wanting something like that!

**Comment by mamarley** [comment]
Also, if you use the Moppy-Advanced branch, you can configure drive pooling so that chords will automatically be played on multiple drives.

**Comment by samphonic** [comment]
Thanks, @mamarley.  I was just thinking today that I should put a link to that branch so it's a little more visible.

**Comment by samphonic** [comment]
Put link to plugin on [wiki](https://github.com/SammyIAm/Moppy/wiki/MIDI-Software), moppy-advanced is the default (only) branch now.
