### ISSUE TITLE
Using Arduino Leonardo built into Lattepanda

### ISSUE THREAD

**Issue by ghost** [samphonic/MoppyClassic#198]
Hi Sam sorry to have to bring this up but I wanted to know if this would work with the lattepanda and how would I go about connecting multiple drives up? I'm familiar with the Arduino uno but not the Leonardo. I know the lattepanda has multiple connectors that allow me to power all the drives directly off the board.

**Comment by samphonic** [comment]
It would appear that the answer is "yes":
https://twitter.com/raidensnakesden/status/992069775965769729
😃 

Nice work!
