### ISSUE TITLE
MB cannot find symbol

### ISSUE THREAD

**Issue by steve-vdb** [samphonic/MoppyClassic#20]
Hi all

Forgive me if i'm being stupid here but I came up against this:

Copied all drivers, and tried the 32 bit versions (I'm running 32 bit win 7)

Did I copy wrong? Or is there something else I'm missing? as far as I can see all the libraries are available, I'm not sure what it's looking for?

Any ideas would be appreciated

init:
Deleting: C:\Program Files\Java\jre6\MoppyDesk\build\built-jar.properties
deps-jar:
Updating property file: C:\Program Files\Java\jre6\MoppyDesk\build\built-jar.properties
Compiling 6 source files to C:\Program Files\Java\jre6\MoppyDesk\build\classes
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:3: cannot find symbol
symbol  : class CommPortIdentifier
location: package gnu.io
import gnu.io.CommPortIdentifier;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:4: cannot find symbol
symbol  : class NoSuchPortException
location: package gnu.io
import gnu.io.NoSuchPortException;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:5: cannot find symbol
symbol  : class PortInUseException
location: package gnu.io
import gnu.io.PortInUseException;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:6: cannot find symbol
symbol  : class SerialPort
location: package gnu.io
import gnu.io.SerialPort;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:7: cannot find symbol
symbol  : class UnsupportedCommOperationException
location: package gnu.io
import gnu.io.UnsupportedCommOperationException;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:24: cannot find symbol
symbol  : class SerialPort
location: class moppydesk.MoppyBridge
    SerialPort com;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:26: cannot find symbol
symbol  : class NoSuchPortException
location: class moppydesk.MoppyBridge
    public MoppyBridge(String portName) throws NoSuchPortException, PortInUseException, UnsupportedCommOperationException, IOException {
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:26: cannot find symbol
symbol  : class PortInUseException
location: class moppydesk.MoppyBridge
    public MoppyBridge(String portName) throws NoSuchPortException, PortInUseException, UnsupportedCommOperationException, IOException {
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:26: cannot find symbol
symbol  : class UnsupportedCommOperationException
location: class moppydesk.MoppyBridge
    public MoppyBridge(String portName) throws NoSuchPortException, PortInUseException, UnsupportedCommOperationException, IOException {
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyMainWindow.java:13: cannot find symbol
symbol  : class CommPortIdentifier
location: package gnu.io
import gnu.io.CommPortIdentifier;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppySequencer.java:3: cannot find symbol
symbol  : class NoSuchPortException
location: package gnu.io
import gnu.io.NoSuchPortException;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppySequencer.java:4: cannot find symbol
symbol  : class PortInUseException
location: package gnu.io
import gnu.io.PortInUseException;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppySequencer.java:5: cannot find symbol
symbol  : class UnsupportedCommOperationException
location: package gnu.io
import gnu.io.UnsupportedCommOperationException;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyPlayer.java:3: cannot find symbol
symbol  : class SerialPort
location: package gnu.io
import gnu.io.SerialPort;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppySequencer.java:32: cannot find symbol
symbol  : class NoSuchPortException
location: class moppydesk.MoppySequencer
    public MoppySequencer(String comPort) throws NoSuchPortException, PortInUseException, UnsupportedCommOperationException, IOException, MidiUnavailableException {
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppySequencer.java:32: cannot find symbol
symbol  : class PortInUseException
location: class moppydesk.MoppySequencer
    public MoppySequencer(String comPort) throws NoSuchPortException, PortInUseException, UnsupportedCommOperationException, IOException, MidiUnavailableException {
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppySequencer.java:32: cannot find symbol
symbol  : class UnsupportedCommOperationException
location: class moppydesk.MoppySequencer
    public MoppySequencer(String comPort) throws NoSuchPortException, PortInUseException, UnsupportedCommOperationException, IOException, MidiUnavailableException {
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyPlayer.java:44: cannot find symbol
symbol  : class SerialPort
location: class moppydesk.MoppyPlayer
    SerialPort com;
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:27: cannot find symbol
symbol  : class CommPortIdentifier
location: class moppydesk.MoppyBridge
        CommPortIdentifier cpi = CommPortIdentifier.getPortIdentifier(portName);
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:27: cannot find symbol
symbol  : variable CommPortIdentifier
location: class moppydesk.MoppyBridge
        CommPortIdentifier cpi = CommPortIdentifier.getPortIdentifier(portName);
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:28: cannot find symbol
symbol  : class SerialPort
location: class moppydesk.MoppyBridge
        com = (SerialPort) cpi.open("MoppyDesk", 2000);
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:29: cannot find symbol
symbol  : variable SerialPort
location: class moppydesk.MoppyBridge
        com.setSerialPortParams(SERIAL_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:29: cannot find symbol
symbol  : variable SerialPort
location: class moppydesk.MoppyBridge
        com.setSerialPortParams(SERIAL_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyBridge.java:29: cannot find symbol
symbol  : variable SerialPort
location: class moppydesk.MoppyBridge
        com.setSerialPortParams(SERIAL_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyMainWindow.java:55: cannot find symbol
symbol  : class CommPortIdentifier
location: class moppydesk.MoppyMainWindow
        Enumeration<CommPortIdentifier> e = CommPortIdentifier.getPortIdentifiers();
C:\Program Files\Java\jre6\MoppyDesk\src\moppydesk\MoppyMainWindow.java:55: cannot find symbol
symbol  : variable CommPortIdentifier
location: class moppydesk.MoppyMainWindow
        Enumeration<CommPortIdentifier> e = CommPortIdentifier.getPortIdentifiers();
26 errors
C:\Program Files\Java\jre6\MoppyDesk\nbproject\build-impl.xml:605: The following error occurred while executing this line:
C:\Program Files\Java\jre6\MoppyDesk\nbproject\build-impl.xml:285: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 1 second)

**Comment by samphonic** [comment]
It looks like you may be missing the reference to the RXTXComm.jar file.  On the left side of the screen in the project area, you should be able to right click on "Libraries" and choose the "Add JAR" option to locate the appropriate RXTXcomm.jar file (the one in the 64-bit drives folder should work fine I think, since Java code isn't as concerned about architecture).

Let me know if that helps.

**Comment by steve-vdb** [comment]
Thanks for the reply, tried that and same problem. The library was there to
begin with, but I removed it and added it again to check, but alas...

Any more ideas?

Thanks for the help

**Comment by samphonic** [comment]
Sorry for the long lag time, my attentions have been diverted from this project for a while.

It really, definitely, looks like you're missing the RXTXComm.jar file.  =P  I know that's not a different idea, but the error messages are basically saying that the compiler can't find the "CommPortIdentifier", "SerialPort", &c. classes, which means that they have not been defined in the current class-path.

Beyond being fairly confident that this is the issue, I unfortunately can't help much in the way of actually solving it for you, as much as I wish I had the correct answer.  Maybe try a "Clean and Build", sometimes that helps with weirdness.

**Comment by steve-vdb** [comment]
No worries about the late reply, your help is appreciated... Will give it
another go at some point.

On Wed, Jun 20, 2012 at 8:14 PM, SammyIAm <
reply@reply.github.com

**Comment by rottt** [comment]
my moppydesk dont run i´ve tried very hard but it doesnt work
the output:

ant -f "C:\Users\Jan Zander\Documents\NetBeansProjects" -Ddebug.class=moppydesk.MoppyUI debug
init:
Deleting: C:\Users\Jan Zander\Documents\NetBeansProjects\build\built-jar.properties
deps-jar:
Updating property file: C:\Users\Jan Zander\Documents\NetBeansProjects\build\built-jar.properties
Compiling 22 source files to C:\Users\Jan Zander\Documents\NetBeansProjects\build\classes
warning: [options] bootstrap class path not set in conjunction with -source 1.5
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\MoppyUI.java:22: error: package org.jdesktop.application does not exist
import org.jdesktop.application.SingleFrameApplication;
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\MoppyUI.java:28: error: cannot find symbol
public class MoppyUI extends SingleFrameApplication {
  symbol: class SingleFrameApplication
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\testing\MoppyFloppySim.java:17: error: package org.jdesktop.application does not exist
import org.jdesktop.application.SingleFrameApplication;
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\testing\MoppyFloppySim.java:23: error: cannot find symbol
public class MoppyFloppySim extends SingleFrameApplication{
  symbol: class SingleFrameApplication
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\MoppyUI.java:48: error: cannot find symbol
            JOptionPane.showMessageDialog(this.getMainFrame(), ex.toString());
  symbol: method getMainFrame()
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\MoppyUI.java:52: error: cannot find symbol
        show(mainWindow);
  symbol:   method show(MoppyControlWindow)
  location: class MoppyUI
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\MoppyUI.java:40: error: method does not override or implement a method from a supertype
    @Override
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\MoppyUI.java:60: error: cannot find symbol
        launch(MoppyUI.class, args);
  symbol:   method launch(Class<MoppyUI>,String[])
  location: class MoppyUI
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\testing\MoppyFloppySim.java:31: error: cannot find symbol
        launch(MoppyFloppySim.class, args);
  symbol:   method launch(Class<MoppyFloppySim>,String[])
  location: class MoppyFloppySim
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\testing\MoppyFloppySim.java:38: error: cannot find symbol
        show(mainWindow);
  symbol:   method show(FloppySimWindow)
  location: class MoppyFloppySim
C:\Users\Jan Zander\Documents\NetBeansProjects\src\moppydesk\testing\MoppyFloppySim.java:34: error: method does not override or implement a method from a supertype
    @Override
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
11 errors
1 warning
C:\Users\Jan Zander\Documents\NetBeansProjects\nbproject\build-impl.xml:915: The following error occurred while executing this line:
C:\Users\Jan Zander\Documents\NetBeansProjects\nbproject\build-impl.xml:307: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 0 seconds)

please help :)

**Comment by samphonic** [comment]
You need to install NetBean's "Swing Application Framework".  You should be able to install it from the addons/plugins menu.

**Comment by rottt** [comment]
Thank you i´ll try this out :)

**Comment by rottt** [comment]
now it works :) thank you

**Comment by samphonic** [comment]
Happy to help.  =)
