### ISSUE TITLE
Converting Moppy to stepper motors

### ISSUE THREAD

**Issue by mattchewr** [samphonic/MoppyClassic#200]
Having issues finding/ converting the moppy code to run on stepper motors. I've been re-writing parts of it to try and work out something but would just like a little direction. I know many people interested in the moppy project have branched out to stepper motors and I would appreciate any resources they, or anyone could offer.

**Comment by samphonic** [comment]
Hey there!  I have some good news and some bad news for you (such is life 😝 ).

The bad news is, I don't think I've done a good enough job redirecting visitors of this repository to [Moppy 2.0](https://github.com/SammyIAm/Moppy2) in its new repository.  You should go check that one out, *especially* if you're trying to adapt the code for any other devices (I've tried to make that a lot easier in the 2.0 build).

The good news is (aside from 2.0 making things slightly easier for supporting new devices), there's already been some work done over there to support the [L298N stepper controller](https://github.com/SammyIAm/Moppy2/blob/master/Arduino/Moppy/src/MoppyInstruments/L298N.cpp), which should be a pretty good example / guide for generally supporting stepper motors.

I'm going to close this issue in favor of issues in the new repository, but if you have questions as you explore the new code *definitely* open up an issue over here and we'll be happy to help!
