### ISSUE TITLE
Issue with jDesktop

### ISSUE THREAD

**Issue by malachipclover** [samphonic/MoppyClassic#21]
I am trying to compile your code in Eclipse Indigo, but i am having trouble.  Steps:
1. Open Eclipse
2. Set the workspace to C:\Users\malachipclover\Downloads\SammyIAm-Moppy-ec7e437\SammyIAm-Moppy-ec7e437\Java\
3. Add new Java project
4. Name it MoppyDesk to purposefully conflict with the MoppyDesk folder inside the Java folder
5. Eclipse creates a project around the existing source
6. In the package explorer pane on the left, it indicates that there is a problem with the project
7. I find out it's in MoppyUI.java
   Error: "The import org.jdesktop cannot be resolved" line 7

I did a web search for jDesktop and all I could find was something for Javascript.
Any help would be appreciated.

**Comment by samphonic** [comment]
Did you try searching for "org.jdesktop"?  The first link is to [this page](http://www.javadesktop.org/articles/JDNC2/index.html), which definitely looks like the library you might be missing.  Give that at try and see if it works.  It's not a library that I manually included; I believe it's part of a NetBeans plugin for UI development.

**Comment by malachipclover** [comment]
Well I really did not want to download NetBeans solely for this but it looks like I'm being forced too...  I've searched but can't seem to find a place to download jDesktop, but I keep seeing that it is usable in Netbeans, so I'm giving it a try.  I'm not liking the 20 minute download time for the smallest package though...

**Comment by samphonic** [comment]
It's less than half the size of the standard Eclipse package, any complaints about speed should be directed at your ISP, rather than the file you're downloading.  Also, I hate to be the bearer of more bad news, but if you didn't like spending time to download the base install, you'll be disappointed to find out that you'll probably also need to install the Swing Application Framework plugin using NetBeans plugin manager.  =/  The base install doesn't seem to include it.

**Comment by malachipclover** [comment]
Weird...  I've downloaded about 3 different Eclipse versions (standard, CDT and EE) and the combined download time for all of them has been smaller than Netbeans' time.  I was thinking about using the jMonkeyEngine IDE that I already have because it is a fork of Netbeans, but I wasn't sure about compatibility, and it slows my computer down to the point where its unusable.  So I jst started the download and then ate.  Installing right now.

**Comment by malachipclover** [comment]
Hmm...  Netbeans is refusing to install any plugins.  I closed it, but then it decided to reopen itself, and then it did some updates.  I hope it works now

**Comment by malachipclover** [comment]
YES!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  After countless hours of Google searching I found some random website hosting bsaf-1.9.jar.zip, and that contained the right packages and it compiled :D  I am swelling with happinesss!!!!
