### ISSUE TITLE
Netbeans Unable to open Zip File?

### ISSUE THREAD

**Issue by pikmin205** [samphonic/MoppyClassic#22]
So, I've been thinking about doing this project for a while, and I finally got a floppy drive, so I have all the parts. I set up all the hardware, and then I got to the software. Everything installed correctly, and when i went to run MoppyDesk in NetBeans, I received this error:

error: error reading C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\RXTXcomm.jar; error in opening zip file
warning: [options] bootstrap class path not set in conjunction with -source 1.5
1 error
1 warning
C:\Documents and Settings\EB\My Documents\NetBeansProjects\MoppyDesk\nbproject\build-impl.xml:915: The following error occurred while executing this line:
C:\Documents and Settings\EB\My Documents\NetBeansProjects\MoppyDesk\nbproject\build-impl.xml:307: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 0 seconds)

I followed all the directions, even including the crtdll.dll, as I run windows XP. I can't figure out what I'm missing, so can someone help? Thanks in advance.

**Comment by samphonic** [comment]
If you navigate in Windows Explorer to C:\Program Files\Java\jdk1.7.0_07\jre\lib\ext\ , do you see the RXTXcomm.jar?  If you manually change the .jar extension to .zip, are you able to open it with Explorer (or WinZip, or whatever).

If you can't open it, it may be that the download of the jar got corrupted somehow and you'll need to try downloading it again.
