### ISSUE TITLE
Option to transpose notes being played

### ISSUE THREAD

**Issue by zhuowei** [samphonic/MoppyClassic#24]
I'm testing Moppy with my internal drive; however, my drive cannot handle high frequencies, so I had to modify Mappy to subtract semitones when calculating the period to make it play at a lower octave.

An actual option to transpose notes down or up to a different key would be really helpful.

**Comment by samphonic** [comment]
I'll leave this open as a future improvement since it would definitely come in handy for quickly playing a MIDI file you didn't create yourself.  I may not get to it myself right away though.

**Comment by samphonic** [comment]
I've added an option to automatically constrain the notes being played to within the floppy's range (C1-B4) by adding or subtracting octaves.

It doesn't let you transpose everything at once though (although I may add that soon), but should at least let you play the songs.
