### ISSUE TITLE
Issue with midi tracks on Moppy

### ISSUE THREAD

**Issue by DefectX11** [samphonic/MoppyClassic#26]
I'm in the process of creating a MIDI file to be used with Moppy, however I'm running into a consistent problem in which all the tracks in my MIDI file are being combined into one when played through Moppy and the floppy drives. I've tried taking a pre-existing MIDI track with enough channels (eight) and just pasting my tracks over top which works almost flawlessly, however it seems some tracks are still being combined (tracks 5 and 6 are both trying to be played on just the fifth drive for some reason when using one of the pre-existing files, and other ones have similar problems).

I suppose it comes down to some strange data stored in the tracks themselves that tells what floppy should play the track, which I personally am not able to make any sense out of. I use Logic Pro 8 if that helps any.

Thanks!

**Comment by samphonic** [comment]
Sorry for the lag, it was Christmas break =D,

I can't help you out specifically with Logic Pro, but it sounds like what you're missing is separate _channels_ for each drive.  Basically, MIDI files can have a number of different "tracks" that contain a bunch of MIDI messages.  Each message is address to a specific "channel" that is usually assigned to a particular instrument, or in this case, a particular floppy drive.  Confusingly, multiple tracks can share a channel, and I think it's even possible for one track to send to multiple channels.

Either way, what you need to do is assign each of the tracks that you are creating to a different MIDI channel.  Like I said, I'm not 100% sure how to do it in Logic Pro 8, but if you're using an "External Instrument" like [this](http://support.apple.com/kb/HT3330?viewlocale=en_US) then I think you just need to assign a different "MIDI Destination" for each track when you're creating the MIDI.  Weirdly, it looks like in Logic Pro that might force each track to a different instrument so things will sound weird (especially if you have 10 or more floppies), but that should do it I think.

Let me know if this helps.

**Comment by DefectX11** [comment]
No worries. This was my friend asking this, so I can't answer too much because I don't have any knowledge of the editing apps he uses. 

We did eventually figure it out, seems to be something with the channels not being assigned properly. Thanks for the response though!

**Comment by samphonic** [comment]
Glad you got it working!
