### ISSUE TITLE
Power supply for the arduino uno

### ISSUE THREAD

**Issue by IDmedia** [samphonic/MoppyClassic#28]
Hi,

This is probably a very silly question, but as this just might become my first arduino uno project, please bear with me. :)

What do you power your arduino uno with? Is the USB-power enought to power it or do I need another external source? Do I have to get an arduino uno power supply or can I just use the ATX power supply for that too? I know that some power supplies do not deliver the right amount of power in all cases, so I just want to be sure...

**Comment by AmEv7Fam** [comment]
USB will be enough to power the Arduino. You will need an external power supply for your floppy drives, though. ;)
