### ISSUE TITLE
Midi files and hardware

### ISSUE THREAD

**Issue by mykolas5b** [samphonic/MoppyClassic#3]
```
       Hi,
```

I've been trying to make my old floppy drive play some music, but being a complete dunce at these kind of things, i need some clarification. I only have one floppy drive, so I should connect the 2nd pin to STEP pin, 3rd pin to DIRECTION pin and then ground? This would play a midi file with 1 channel? Or am i messing something up? So far the floppy drive doesn't respond to any track i play.

**Comment by samphonic** [comment]
Sounds like you're close.  
- Arduino pin 2 goes to the STEP pin, and Arduino pin 3 goes to the DIRECTION pin.
- One of the floppy's ground pins (any of the odd-numbered pins on the floppy drive) needs to be connected to the GND pin on the Arduino.
- You will need to connect the appropriate Drive Select pin on the floppy drive to ground as well.  It'll probably be pin 12 or 14 on the floppy drive, which you can just connect to the pin directly below it on the drive (i.e. you could connect pin 12 to pin 11, or pin 14 to pin 13).  This was a little different for different drives I used, but you'll know you have it right when the LED on the front of the drive comes on.

Let me know if that helps you out.  If you're still having issues, make sure the LED on the drive is on (it needs to be one before the drive will "listen" for commands from the Arduino.

**Comment by mykolas5b** [comment]
Thanks, it does work now,although very sloppy, most tracks start out nice and then stop and resume skipping parts of the tune, is this caused by notes being too high or low? I've tried tetris, kirbys, imperial march and super mario themes and in all of them the floppy skips parts.

**Comment by samphonic** [comment]
That's a possibility.  The sample MIDIs that are in the source code SHOULD work fine, though keep in mind that those were written for either 4 or 8 floppy drives, so if you only have one drive hooked up, you'll only be getting channel 1 of the MIDI file (which might only contain some parts).

Glad it's working for you (sorta), though!
