### ISSUE TITLE
Wiki page for MIDI-editing software?

### ISSUE THREAD

**Issue by AmEv7Fam** [samphonic/MoppyClassic#33]
I was thinking about making a Wiki page listing software capable of editing the MIDI files. Perhaps categorizing it by type, then in the table: its name and a link to it, potential cost, and pefhaps other things as needed...

**Comment by samphonic** [comment]
Sounds like a great idea!  I'm still learning this GitHub thing; can you just create and edit the page yourself, or is there something I have to do to give you that access?

**Comment by AmEv7Fam** [comment]
I can create and edit the page myself; however, I'm also relatively new to GitHub and Wiki stuff.

Anyone willing to start it for us?

Got it started at https://github.com/SammyIAm/Moppy/wiki/Software, but alas, I show my new-ness.... haha

**Comment by AmEv7Fam** [comment]
Bit of a bump... Anyone still willing to help me out? I know of only two or three programs to edit MIDI files.

**Comment by felixphew** [comment]
I might be able to add a few...

**Comment by samphonic** [comment]
Made [the page](https://github.com/SammyIAm/Moppy/wiki/MIDI-Software) a bit better, but feel free to add more.  :)
