### ISSUE TITLE
Android version?

### ISSUE THREAD

**Issue by AmEv7Fam** [samphonic/MoppyClassic#34]
I think I may have casually mentioned it a year ago in a YouTube comment, but now I'd love to see an Android version of this. Especially since I have a tablet with a USB port.

**Comment by samphonic** [comment]
Anyone's welcome to give it a shot (yay open source!).  Since Android generally supports Java, you wouldn't have to change too much.  The UI and the serial communications would probably the only parts that need to be modified.

**Comment by AmEv7Fam** [comment]
May just have to build to see how far it gets.....

Do have NBAndroid on my machine....

**Comment by AmEv7Fam** [comment]
Making a fork of it. So that's what mine is.

**Comment by AmEv7Fam** [comment]
Bit of a bump, but I've been doing a bit of research on it.

The two issues:

Getting the tablet to talk to the Arduino.
Porting the UI to Android tablet.

I'm gonna nuke my current fork, re-create it, and make an android branch.

**Comment by AmEv7Fam** [comment]
Android branch created. Now, to get it working... haha....

**Comment by samphonic** [comment]
Closing this for now, but if you do get a fork working, you can add it to the (currently very short) list of ports on the [FAQ](https://github.com/SammyIAm/Moppy/wiki/FAQ)
