### ISSUE TITLE
Multiple Arduinos

### ISSUE THREAD

**Issue by DigitallyRemastered** [samphonic/MoppyClassic#35]
So, I've tried using Multiple Arduinos.

It works in the sense that I can use two arduinos at once, but I cannot assign midi channels 9 through 16 to any of the drives on either arduino. Thus I can't make use of 16 floppy drives at a time.

What is to be done on this matter? I just checked the MoppyCOMBridge and the MoppyPlayerOutput files, and I'm not even sure how I'm able to use two arduinos at the same time in the first place. Also confused on the role of the ReceiverMarshaller :/

Any help is appreciated!

**Comment by samphonic** [comment]
Hello there,

When you say you "cannot assign midi channels 9 through 16 to any of the drives on either Arduino", I assume you mean that you tried in the interface, and the Arduinos didn't play any notes?

The Arduino software is coded only for channels 1 through 8 (mapped to pins 2-16).  You can do a quick modification to the code for the second Arduino on line 98 to change:

``` c
currentPeriod[Serial.read()] = (Serial.read() << 8) | Serial.read();
```

to 

``` c
currentPeriod[max(0,Serial.read()-16)] = (Serial.read() << 8) | Serial.read();
```

Which will basically subtract 16 from the pin number for that Arduino (i.e. channel 9 on pin 18 will now be directed to pin 2, channel 10 will be directed to 4, &c.).  The max() function makes sure we don't try writing to a negative array index, which could do some weird stuff, I imagine.

I haven't actually tested this, but it seems pretty likely to work.  Let me know how it goes.

It would be ideal, probably, to allow you to map each channel to a device, and a specific channel on that device.  Maybe I (or someone) will add that some day, but for now, I think this'll get you going.

**Comment by DigitallyRemastered** [comment]
O, o so simple, yet so elegant! Only problem was that the max command seemed to mess with things... I have no idea why - that seemed like a good catch. After finding that max() wouldn't work, I tried writing an if statement with the condition if(Serial.read() > 17) and that didn't work either... However, simply subtracting 16 seems to work fine! So replacing:

 currentPeriod[max(0,Serial.read()-16)] = (Serial.read() << 8) | Serial.read();

with

currentPeriod[Serial.read()-16] = (Serial.read() << 8) | Serial.read();

seems to work fine =D

Thanks a lot Sammy! I thought I was gonna have to try to get the Java part to assign sets of channels to individual arduinos. Keep on keep'n on.

**Comment by samphonic** [comment]
Glad you got it working!  Weird that it had issues with max, and your "> 17" check.  Nice job working around my guesses though!
