### ISSUE TITLE
Using 2 Arduino Uno Cards to play on 16 Drives

### ISSUE THREAD

**Issue by Lync1** [samphonic/MoppyClassic#36]
Hi SammyIAm,

I have set up 2 Arduino Uno Cards with 8 Drives on each card.
In Moppy Advanced you have the option of which COM port you want to send each channel to.
I cannot get Moppy Advanced to play channels 9 - 16.
I hope it is as easy as altering the code in Timer1 to get the data from channels 9 - 16 instead of channels 1 - 8, then uploading this code to the 2nd Arduino Card?

Could you tell me how can I do this?
(I have also sent you a tweet with my email address if you could reply to this?)

Lyndon.

**Comment by samphonic** [comment]
Check out [this issue](https://github.com/SammyIAm/Moppy/issues/35) for the solution.

It's basically, as you predicted, just a small change to the Arduino code for the second Arduino.
