### ISSUE TITLE
Need help getting this to work, drives are not responding

### ISSUE THREAD

**Issue by Grix** [samphonic/MoppyClassic#41]
I tried building a 3-drive setup for a weekend project, but I can't get it to work.. No matter what I do, I can't seem to get the floppy drives to respond to anything, they just sit there silently. Here's what I've done:

Connected power to the floppy drives
Connected the dir and step pins to the arduino according to the readme.
Connected the pins below the dir and step to ground.
Bridged the drive select pin and pin below it (drive LED lights up)
Flashed my arduino with moppy.ino after installing Timer1
Downloaded JDK w/ netbeans
Copied the serial drivers as directed in the readme file

But when I start the moppydesk program and play a midi file, nothing happens. I've verified with a multimeter than the digital pins are actually outputting the data but the floppy disks are not responding. What could be wrong? Do I need to bridge more pins, like motor enable or something? Is there any troubleshooting I can do with the drives to see if they are working properly?

**Comment by Chong-McBong** [comment]
are you sure that you connected the floppy ground to the arduino ground? without it, the step commands won't arrive, as the circuit is incomplete. most of the bottom row of pins is ground, so there are a few options to connect to.. 
some floppy drives have the ribbon cable connected upside-down, and some have various pins missing from the bottom row, maybe just check your pins by re-arranging them, and double checking they are in the correct spot. 

this pic shows the layout i used for wiring up the drives, hopefully it will be of some use :)
![floppy moppy pin layout](https://f.cloud.github.com/assets/5050841/1509721/9b453386-4a5e-11e3-858e-7d9251dc6704.JPG)

**Comment by Grix** [comment]
Thanks, got to work. For the record, there were two problems: 1) I didn't have any floppy disks in the drives, didn't know that was necessary, and 2) I had to move the step and dir wire one notch to the right on the connector

**Comment by samphonic** [comment]
Glad you got it working!  And thanks, @Chong-McBong for that picture; that's super-handy.  =)

As a quick side note, none of the floppy drives I've worked with actually require that a disk be inserted (mine are actually a lot quieter with disks in them), so you might give it another try without the disk.  On the other hand, there's a lot of different models of floppy drives out there...
