### ISSUE TITLE
moppy advanced : where is the usb port drop-down ?

### ISSUE THREAD

**Issue by gorhgorh** [samphonic/MoppyClassic#44]
hi there, thanks for giving us this wonderful program that makes wishes comes true :) 
sorry to bother with such a simple question but, i installed Moppy and can make the simple version working like a charm. 

but i'm looking to use the advanced version, that compiles well too, but, reading the instruction i find this 

```
Select the COM port that the Arduino is hooked up to from the "Arduino Port" drop-down.
```

but i just can't find the drop down menu you are talking about :)

if you can please enlighten me i would be a glad floppy lover .

thanks in advance

**Comment by samphonic** [comment]
Hi there, thanks for taking an interest in the project.  =)

On Moppy Advanced, on the right side of the screen, tick the check boxes for each MIDI channel you want to use.  Select the "Moppy" radio button, and then choose the appropriate COM port from the drop-down menu for that channel.

If you're doing this on a non-Windows machine, the ports may be labeled something more like "tty", but it'll be the same as you selected in the Arduino IDE to upload the software there.

**Comment by gorhgorh** [comment]
ok i see now i was looking for something to configure BEFORE the build, thanks. 

I'll now dive in the midi system to be able to play it live
