### ISSUE TITLE
New Ideas

### ISSUE THREAD

**Issue by knorke74** [samphonic/MoppyClassic#45]
Hey Sammy,

it's been over a year now since I last worked on my "Moppy Project". Now my floppies want to get to work again ... and I am thinking about a "headless" standalone version where I don't need a separate computer running while playing music on the floppy organ. A lot of work ahead now ... especially on the Java side ...

And, Sammy, could I please request your "Imperial March" midi file? I'm not very good at midi-composing for the floppies yet, and that song is so cool! ... Would have written you an e-mail about it, but I can't find a contact address anywhere...

That would be so cool, many thanks in advance!

Cheers

Thorsten

**Comment by samphonic** [comment]
Hello there,

I wish you the best of luck on the headless project.  It's definitely an achievable goal, but you'll probably need something more powerful than an Arduino to store and interpret the MIDI files (maybe a Raspberry Pi).

I don't want to post my email in these tickets, but I don't see a direct messaging option for github.  If you send me a direct message to @Sammy1Am on Twitter or YouTube with your email address, I'll send along the MIDI for you.

**Comment by knorke74** [comment]
Indeed, a Raspberry Pi it will be. 

Thank you so much, I will try to contact you.

Cheers, Thorsten

**Comment by jazzbassNick** [comment]
Just to piggy back on this concept, I'm thinking a standalone, with SD card shield to hold midi files and  and a Display shield to navigate and choose files. Wondering if anyone has played with Moppy & http://haiku-vm.sourceforge.net/ yet?

I'm looking forward to going down this road to see where it leads ;)

**Comment by samphonic** [comment]
Closing due to lack of "issue".  Feel free to continue your discussion here though.  If you get any ports up and running, make sure to add them to the list on the [FAQ](https://github.com/SammyIAm/Moppy/wiki/FAQ).
