### ISSUE TITLE
Linux - Fedora 19 - compiling in neatbeans ide 7.4 errors:

### ISSUE THREAD

**Issue by maglinvinn** [samphonic/MoppyClassic#46]

**Comment by maglinvinn** [comment]
warning: [options] bootstrap class path not set in conjunction with -source 1.5
/home/deakin/Documents/Moppy-master/Java/MoppyDesk/src/moppydesk/MoppyUI.java:7: error: package org.jdesktop.application does not exist
import org.jdesktop.application.SingleFrameApplication;
/home/deakin/Documents/Moppy-master/Java/MoppyDesk/src/moppydesk/MoppyUI.java:13: error: cannot find symbol
public class MoppyUI extends SingleFrameApplication{
  symbol: class SingleFrameApplication
/home/deakin/Documents/Moppy-master/Java/MoppyDesk/src/moppydesk/MoppyUI.java:20: error: cannot find symbol
        show(mainWindow);
  symbol:   method show(MoppyMainWindow)
  location: class MoppyUI
/home/deakin/Documents/Moppy-master/Java/MoppyDesk/src/moppydesk/MoppyUI.java:17: error: method does not override or implement a method from a supertype
    @Override
/home/deakin/Documents/Moppy-master/Java/MoppyDesk/src/moppydesk/MoppyUI.java:27: error: cannot find symbol
        launch(MoppyUI.class, args);
  symbol:   method launch(Class<MoppyUI>,String[])
  location: class MoppyUI
Note: /home/deakin/Documents/Moppy-master/Java/MoppyDesk/src/moppydesk/MoppyMainWindow.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
1 warning
/home/deakin/Documents/Moppy-master/Java/MoppyDesk/nbproject/build-impl.xml:920: The following error occurred while executing this line:
/home/deakin/Documents/Moppy-master/Java/MoppyDesk/nbproject/build-impl.xml:300: Compile failed; see the compiler error output for details.
BUILD FAILED (total time: 0 seconds)

i'm at a loss.  what can i do to get this to work?

**Comment by samphonic** [comment]
You're missing the Swing Application Framework in Netbeans.  Just go to the plugin manager and install this, and you should be good to go.  =)

**Comment by maglinvinn** [comment]
[root@localhost 1moppy]# java -jar MoppyDesk.jar 
Experimental:  JNI_OnLoad called.
WARNING:  RXTX Version mismatch
    Jar version = RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net
    native lib Version = RXTX-2.1-7
RXTX Warning:  Removing stale lock file. /var/lock/LCK..ttyUSB0
^C[root@localhost 1moppy]# java -jar MoppyDesk.jar 
Experimental:  JNI_OnLoad called.
WARNING:  RXTX Version mismatch
    Jar version = RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net
    native lib Version = RXTX-2.1-7
Loaded sequence with 5 MIDI channels.
#

# A fatal error has been detected by the Java Runtime Environment:

#

# SIGSEGV (0xb) at pc=0x00007fd8f556b733, pid=14635, tid=140569818879744

#

# JRE version: OpenJDK Runtime Environment (7.0_45-b15) (build 1.7.0_45-mockbuild_2013_10_16_17_47-b00)

# Java VM: OpenJDK 64-Bit Server VM (24.45-b08 mixed mode linux-amd64 compressed oops)

# Problematic frame:

# C  [librxtxSerial.so+0x7733]  Java_gnu_io_RXTXPort_nativeDrain+0xc3

#

# Core dump written. Default location: /home/deakin/Documents/1moppy/core or core.14635

#

# An error report file with more information is saved as:

# /tmp/jvm-14635/hs_error.log

#

# If you would like to submit a bug report, please include

# instructions on how to reproduce the bug and visit:

# http://icedtea.classpath.org/bugzilla

#
Aborted (core dumped)

when i tried to run it withthe version i compiled on my windows machine i got this, but at least i got it to run up till the point i tried to start the song :D  i imagine its cause i compiled on windows and am trying to run it on linux?  maybe they're related?  going to see if i can't find this plugin manager and resolve (i'm not very familiar with netbeans)

Seems weirdly related since with that plugin i got this error instead:

warning: [options] bootstrap class path not set in conjunction with -source 1.5
Note: /home/deakin/Documents/Moppy-master/Java/MoppyDesk/src/moppydesk/MoppyMainWindow.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
compile:
run:
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at moppydesk.MoppyMainWindow.updateComSelectionMenu(MoppyMainWindow.java:55)
    at moppydesk.MoppyMainWindow.<init>(MoppyMainWindow.java:43)
    at moppydesk.MoppyUI.startup(MoppyUI.java:19)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by maglinvinn** [comment]
that being weird cause the jar i created, started from command line doesn't throw an error, cause RXTX files are in the right folders.  The RXTX install manual doesn't match what my paths are though perfectly... 

```
java.library.path = /usr/java/packages/lib/amd64
    /usr/lib64
    /lib64
    /lib
    /usr/lib
```

**Comment by maglinvinn** [comment]
egad, sorry about that, github totally reformatted the copy/pasta from my ide.

**Comment by maglinvinn** [comment]
-rwxr-xr-x. 1 root root 138573 Dec 19 15:57 librxtxSerial.so
/usr/java/jre1.6.0_02/lib/amd64
-rw-r--r--. 1 root root  59464 Dec 19 15:55 RXTXcomm.jar
/usr/java/jre1.6.0_02/lib/ext

but ... i should mention i have two javas on this machine (work machine don't ask me why)... how do i know which java the IDE is working with?

**Comment by maglinvinn** [comment]
oooh.  nvm.  got it :D

ended up being in NOT the java.library.path location.

Now i just gotta figure out how to get the application to run the control version and not the main desk.

**Comment by samphonic** [comment]
Whoa!  That was rather surprising.  =P
The important line is right at the very top:
`Jar version = RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net
native lib Version = RXTX-2.1-7`

The jar file referenced in the Moppy project is from version 2.2-20081207 of rxtx, but the library installed on your machine is version 2.1-7.  Unfortunately, I can't give you sure-fire way to solve this since it's pretty environment-specific, but here's some things to try:
- Since the native lib is probably going to be harder to replace, try downloading an RXTX jar file to match version 2.1-7.
- There should be some configuration somewhere in NetBeans that specifies which java you're using.  I don't know off hand where it would be, but Google might be able to here

**Comment by samphonic** [comment]
Ah, good, okay.  Glad you got it working now!

**Comment by maglinvinn** [comment]
So.  I gotta ask 

when i ran this at home i got a window that was 2 columns.  Left was the file and some sort of sequence thing.  right was channels, what port, and enable/disable.  

When i run moppy_master, which contains the moppy desk utility, from here at work, i get a single window with tabs, connection is empty, bridge? coming soon, etc etc.  do i have the wrong project or something?

**Comment by maglinvinn** [comment]
check_group_uucp(): error testing lock file creation Error details:Permission deniedcheck_lock_status: No permission to create lock file.
please see: How can I use Lock Files with rxtx? in INSTALL

well, at least i'm getting a new error.

lock:x:53:deakin

i see no uucp group?

**Comment by maglinvinn** [comment]
^C[root@localhost 1moppy]# java -jar MoppyDesk.jar 
Experimental:  JNI_OnLoad called.

# Stable Library

Native lib Version = RXTX-2.1-7
Java lib Version   = RXTX-2.1-7
RXTX Warning:  Removing stale lock file. /var/lock/LCK..ttyUSB0
Loaded sequence with 5 MIDI channels.
#

# A fatal error has been detected by the Java Runtime Environment:

#

# SIGSEGV (0xb) at pc=0x00007fbb95473733, pid=3041, tid=140443958667008

#

# JRE version: OpenJDK Runtime Environment (7.0_45-b15) (build 1.7.0_45-mockbuild_2013_10_16_17_47-b00)

# Java VM: OpenJDK 64-Bit Server VM (24.45-b08 mixed mode linux-amd64 compressed oops)

# Problematic frame:

# C  [librxtxSerial.so+0x7733]  Java_gnu_io_RXTXPort_nativeDrain+0xc3

#

# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

#

# An error report file with more information is saved as:

# /tmp/jvm-3041/hs_error.log

#

# If you would like to submit a bug report, please include

# instructions on how to reproduce the bug and visit:

# http://icedtea.classpath.org/bugzilla

#
Aborted (core dumped)

Ugh.  so close.  over wrote local librxtx...so file one by one finally got the software to load without apparent glitch, second i tried to 'start' the song, this.  its segfaulting on librxtxSerial.so that comes with the moppy.zip.  i guess i'll try the file direct from their site.

**Comment by maglinvinn** [comment]
ugh.  again with the formatting thing.  thanks github.

**Comment by samphonic** [comment]
So there are two branches of Moppy available.  One is just the default "master" branch, but the one you downloaded originally is the moppy-advanced branch.  Of the two, the moppy-advanced has been more recently updated, so I recommend using that one.

As far as the locking thing or the other error, I haven't seen either of them before, so I'm not sure.  Maybe try getting the code for moppy-advanced first and see if that fixes anything.

**Comment by maglinvinn** [comment]
Yeah... i just found the advanced, ran it, zero problems, right up to the point i tried to 'play' the song to the serial connection:

ant -f /home/deakin/Documents/Moppy-moppy-advanced/Java/MoppyDesk -Dnb.internal.action.name=run run
init:
Deleting: /home/deakin/Documents/Moppy-moppy-advanced/Java/MoppyDesk/build/built-jar.properties
deps-jar:
Updating property file: /home/deakin/Documents/Moppy-moppy-advanced/Java/MoppyDesk/build/built-jar.properties
compile:
run:
RXTX Warning:  Removing stale lock file. /var/lock/LCK..ttyUSB0
Loaded sequence with 5 MIDI channels.
#

# A fatal error has been detected by the Java Runtime Environment:

#

# SIGSEGV (0xb) at pc=0x00007fae68c795da, pid=4206, tid=140387064575744

#

# JRE version: OpenJDK Runtime Environment (7.0_45-b15) (build 1.7.0_45-mockbuild_2013_10_16_17_47-b00)

# Java VM: OpenJDK 64-Bit Server VM (24.45-b08 mixed mode linux-amd64 compressed oops)

# Problematic frame:

# C  [librxtxSerial.so+0x75da]  Java_gnu_io_RXTXPort_nativeDrain+0xea

#

# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

#

# An error report file with more information is saved as:

# /tmp/jvm-4206/hs_error.log

#

# If you would like to submit a bug report, please include

# instructions on how to reproduce the bug and visit:

# http://icedtea.classpath.org/bugzilla

#
Java Result: 134
BUILD SUCCESSFUL (total time: 34 seconds)

full output, same error, segfault in librxtx.  _sigh_  what sucks is i can't do anything arduino without figuring this out.

**Comment by samphonic** [comment]
I assume you've tried updating your librxtx the standard package-manager way.  You might have some success finding/building a newer version of librxtx from source?  Wish I had more to offer.

**Comment by maglinvinn** [comment]
yah man.  i'm thinking of swithcing my workstation to ubuntu.  there's a lot more information how to fix this for that distro.  lol.

**Comment by samphonic** [comment]
Unless you have very specific requirements for a certain OS, that's how I'd recommend choosing a flavor of Linux.  The more popular, the more likely there will be support and up to date software.  I've been pretty happy with Mint too, which is built on top of Ubuntu (I believe).

**Comment by maglinvinn** [comment]
So, i switched to ubuntu, you mentioned a package manager solution for librxtx, but i'm not finding it for apt-get.  GOt any suggestions?

**Comment by samphonic** [comment]
Google is always a good place to start.  ;P
But in seriousness, the package is called "librxtx-java"-- it should definitely be available in apt-get.

**Comment by maglinvinn** [comment]
```
    System.out.println("***************");
    System.out.println(System.getProperty("java.library.path"));
    System.out.println("***************");
```

added this cause i was getting frustrated

which then rendered this just before the error:

---

../SerialDrivers/rxtx-2.1-7-bins-r2/Windows/ch-rxtx-2.2-20081207-win-x64;${env_var:PATH}

---

why in the world is it looking for Windows on my linux system?  i just uncompressed from github and loaded with neatbeans :P  its no wonder it can't find my RXTX files   ... or am i completely going in the wrong direction?

**Comment by maglinvinn** [comment]
and for what its worth - 

librxtx-java is already the newest version.

straight from the apt-get mouth :D

**Comment by samphonic** [comment]
The NetBeans project might have an argument configured that will search in that path for libraries.  You can edit this argument by right clicking on the project and going to properties... and then maybe a section entitled something like "Run"?  I haven't been in there for a while, so I don't know off hand.

That said, adding a path that doesn't exist won't cause any errors, there just won't be any library found at that path (it wouldn't have helped anyway, because it would have been for Windows).  You need to make sure your actual librxtx library _is_ in your path though.  You can manually edit the path arguments in the NetBeans project properties, or you could modify your PATH environment variable to include the path to the library.

There may be more specific instructions on this available on any site detailing rxtx usage on Linux.

**Comment by maglinvinn** [comment]
well, i manged to get past all that jump and jive, got netbeans to compile it, and then could run it from command line... but then got this new error.

http://pastebin.com/rYHPZgAm

is this anything you recgonize?

**Comment by maglinvinn** [comment]
for what its worth, i hit connect, it says it connected, and then i sent it a stop/reset, and it made this error.  i also tried starting a song, same error. _sigh_  :)

**Comment by samphonic** [comment]
A quick Google of the error turned up this thread:
http://forums.xilinx.com/t5/Installation-and-Licensing/SDK-segfault-on-UART-output/td-p/160000
among others that seem to suggest that Arduinos and 64bit Ubuntu distributions don't always play nice.  The solution seems to be using a different librxtxserial.so (like rxtx2.2pre2 as suggested in the link above)

**Comment by maglinvinn** [comment]
Dude.  that totes fixed it.  wizard r u.  :D  thanks man

**Comment by samphonic** [comment]
Hooray!
