### ISSUE TITLE
Arduino not sending signals

### ISSUE THREAD

**Issue by Thedr001** [samphonic/MoppyClassic#50]
Hi,

Sorry I am still new to the arduino and I love the potential of this project however I am having an issue getting the arduino to run the drive. I can confirm that my drive is working and wired up right as I can take the wires to the arduino and tap them together to get the drive to move in both directions however I cannot get the program to play on the drive. It connects fine with no errors and I can see the RX light flash as I'm playing the music but nothing happens on the drive.

Any help you can offer would be amazing!

Thanks,
Thedr001.

**Comment by samphonic** [comment]
Things to double-check:
- Make sure the Arduino code actually compiled and uploaded to the Arduino.  (Look for errors in the console at the bottom of the IDE when you hit the upload button)
- Double check that you've got the step pin on the drive connected to pin 2 on the Arduino.  Maybe switch pins 2 and 3 around just to check.
- Make sure your drive is grounded to the Arduino's ground pin.
- Try one of the sample MIDIs.  Basically, make sure that your MIDI file is using channel 1.

**Comment by Thedr001** [comment]
Hi SammyIAm,

I get the following error when I run the program, but I looking at other areas of your project I think you say this is normal:

Jan 11, 2014 9:46:03 PM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.id using MoppyUI
Jan 11, 2014 9:46:03 PM org.jdesktop.application.LocalStorage getId
WARNING: unspecified resource Application.vendorId using UnknownApplicationVendor

I've tried swapping the cables around.

The ground pin is in slot 14(ground) if I take the cable out and tap it against the step and direction pins the drive moves.

I've tested it with all of your sample midis.

Thanks for your quick response btw!

-TheDr001

**Comment by samphonic** [comment]
Sorry, less quick response this time around:

You are correct, neither of those warnings is an error, so there's nothing to worry about there.

Did you try re-uploading the software to the Arduino?  Sometimes the errors during compile and upload in the Arduino  IDE are very subtle.

**Comment by Thedr001** [comment]
Ok, so I made a huge mistake.

Totally forgot to actually compile and send code to the arduino. /facepalm

Thanks so much for your help and I can happily report that it is now working perfectly.
