### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by philipsteffan** [samphonic/MoppyClassic#53]
I was wondering what license Moppy uses.

I'm asking because I just wrote a floppy music how-to for a magazine, including Moppy, and was wondering if I could offer binaries for novice readers to download so they don't have to toy around with Java unless they really want to.

**Comment by samphonic** [comment]
That is an excellent question!

I haven't actually picked a licence for it, but probably should at some point.  For now though, I would say it should be treated like a CC-Attribution licence.  Basically, as long as there's some sort of link or attribution back to me (preferably just to this GitHub repo), then everyone has my permission to do whatever the heck they want with the code.  =)

On a side note, if you DO end up making binaries available, I would love to provide a link to them in the read me; several people have asked for them, but I've never got around to building any myself.
