### ISSUE TITLE
GUI doesnt show up even though build is complete and no errors

### ISSUE THREAD

**Issue by ljmerza** [samphonic/MoppyClassic#57]
Hi, I opened a moppy project in my netbeans and added the rxtxcomm.jar file to the library. the project was still giving me a org.jdesktop.application does not exist  error so i added the appframework-1.0.3.jar file and it fixed that issue.  There seems to be no errors and the build completes successfully but nothing happens. 

Here's my project
![capture](https://f.cloud.github.com/assets/4085765/2215877/f151c020-99fd-11e3-98ae-335cdace4c2f.JPG)

info:
Windows 8.1 x64
JRE 7.1 x86 with rxtxcomm x86 files in correct folders
netbeans 7.4

Thanks.

**Comment by samphonic** [comment]
Huh, interesting.  It does look like you created a new project in NetBeans and tried to import the code from the Moppy project though.  The download from GitHub should already be a valid NetBeans project-- try using NetBeans to just open the downloaded project, rather than creating a new one.

**Comment by ljmerza** [comment]
Hey, thanks for responding. I opened the netbeans project and it seems to auto load all of the necessary libraries but now when I run the program i get this error:

Feb 20, 2014 3:42:22 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Qt: Untested Windows version 6.2 detected!
l

netbeans wouldnt let me copy the rest so here is a picture of it:
![capture](https://f.cloud.github.com/assets/4085765/2223232/cd43fe06-9a6f-11e3-9fbf-59de76229098.JPG)

**Comment by samphonic** [comment]
Are you sure there's not another error in there somewhere?  The text you pasted has to do with reading preferences from the registry, but the stacktrace looks like it's trying to load the rxtx assembly.  Can you export the log to text somehow to paste it here?

**Comment by ljmerza** [comment]
i tried exporting but half of it came out as random characters.  I did miss a part of the error code. This is what is in between the text and picture in the last post i made.
![capture](https://f.cloud.github.com/assets/4085765/2226080/6f08dfb0-9a9b-11e3-8252-9730f0836a3d.JPG)

the text that extends out is:
projects\Moppy-moppy-advanced\Java\SerialDrivers\rxtx-2.1-7-bins-r2\Windows\ch-rxtx-2.2-20081207-win-x64\rxtxSerial.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: C:\Users\Leo\Dropbox\arduino kinect projects\Moppy-moppy-advanced\Java\SerialDrivers\rxtx-2.1-7-bins-r2\Windows\ch-rxtx-2.2-20081207-win-x64\rxtxSerial.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform

maybe it doesnt like my 32bit rxtxcomm files but my java is x86.

EDIT: Okay so here's the fix.  Looks like your program will auto load the appropriate bit version of the dll files based off the OS so if you have a x86 java on a x64 system, it errors out.  I just replaced the x64 drivers in the folder its erroring out on (Moppy-moppy-advanced\Java\SerialDrivers\rxtx-2.1-7-bins-r2\Windows\ch-rxtx-2.2-20081207-win-x64) with the x32 drivers and it works just fine.

Thank you for the help. Awesome that you provide support after all this time.

**Comment by ljmerza** [comment]
Damn I spoke too soon.  The GUI loads now but it errors out when trying to connect to the arduino.
![capture](https://f.cloud.github.com/assets/4085765/2226556/9ce4827a-9aa7-11e3-937c-154fecdd2b8d.JPG)
![capture2](https://f.cloud.github.com/assets/4085765/2226557/9ce5a48e-9aa7-11e3-92a1-84ece83b7887.JPG)

**Comment by samphonic** [comment]
Okay, you've made some progress then.  I think the issue is probably coming from the version mismatch (you can see the warning about it there in white in your latest screenshot).

Basically, the rxtx.jar file that I included is a newer version than the dll file that you're referencing.  You can resolve this by either downloading a newer version of the dll (from rxtx.cloudhopper.net probably), or by using the jar file that came with the dll that you're currently using (from whatever site you got the dll from).

I'd recommend using a newer version of the dll, but either should work.

**Comment by ljmerza** [comment]
That link is dead but I was able to find a download and get it all working. Thanks again!

**Comment by jazzbassNick** [comment]
You know, that's funny - I get the same mismatch warning, but don't have any issues. Hmmm....

**Comment by samphonic** [comment]
Glad you got it working!

@jazzbassNick : That is a little unusual, but that's why the warning is just a "warning" and not an "error": it won't _necessarily_ break anything, but you should watch out for it.  I'm guessing the issue was related to the fact that he was using Windows 8 (Windows version 6.2 'cus Microsoft is bad a version numbers), and the dll's weren't happy.
