### ISSUE TITLE
Old 5.25" drive support?

### ISSUE THREAD

**Issue by charredUtensil** [samphonic/MoppyClassic#58]
I have an even older 5.25" floppy drive with my rapidly growing collection of (now six) 3.5" drives. other problems aside, (the volume on these things is entirely inconsistent) the 5.25" drive seems to have half the steps that the other drives do. That is, it will spend half a cycle playing its note properly and the other half banging against the end of its track. The banging is INCREDIBLY LOUD compared to the other six combined (louder than the speakers on my Mac, too), is roughly an octave lower, and is slightly off key. Removing the reverse pin causes it to play notes like this constantly, but it's not great, because it overshadows all the other drives, is an octave lower, and is off key. I'd imagine this isn't the only one with such a problem. Any ideas? Is there a setting somewhere to tell Moppy that the track on one drive is half as long as it normally expects?

**Comment by tg44** [comment]
If I understend you correctly, in the arduino side you coud tell the maximum allowed position in line 23-24.

The loudness is a problem, I'm thinking the solution too, but I dont go so far...

**Comment by charredUtensil** [comment]
Realizing now that I wrote this at 2:30 in the morning with half a brain. It'd be nice to set this stuff dynamically vs. hard coding it but w/e closing

**Comment by samphonic** [comment]
Hey, at least I put the variables in a nice array at the beginning.  It could have been worse.  ;P

But yeah, in this case, hard coding seemed an acceptable solution since it's unlikely that a given drive is going to change from 3.5" to 5.25" very often once you've got things set up.  (Also simpler code means it's more likely to work)
