### ISSUE TITLE
Software or hardware issue?

### ISSUE THREAD

**Issue by ghost** [samphonic/MoppyClassic#60]
My Floppy Drive don't work well with Floppy Desk. The stepper motor does one movement sometimes, and goes next when I click on the "reset/stop" button. I think I'm near the solution, but I need a little help! Could you help me please? Sorry for my english. If something is not clear, you can ask me. Good job! It's an amazing project!

**Comment by samphonic** [comment]
If the drives response when you press the stop/reset button, you are indeed close to having it working.

Try switching the "step" and "direction" pins.

**Comment by ghost** [comment]
Thank you! Now it's amazing! =)

**Comment by samphonic** [comment]
Glad it's working! =)
