### ISSUE TITLE
Pitching is glitching?

### ISSUE THREAD

**Issue by tg44** [samphonic/MoppyClassic#63]
Hy!

I wrote a midi splitter (https://github.com/tg44/MidiSplitter), and I get a future req (https://github.com/tg44/MidiSplitter/issues/3). I implemented the simple "get the pitch note and write it down" technic (like the moppy do), but there is a glitch where I dont do anything with command messages. Its a possible glitch in your software too.

(I cant implement a good solution while Im not refactoring my whole code, but the moppy can resolve this I think easily.)

I dont req this, just sayin :)

**Comment by samphonic** [comment]
Moppy (at least Moppy Advanced, but I'm pretty sure the old one too) already supports pitch-bending by reading the "pitch bend change" messages from the MIDI file, and telling the Arduino to compensate accordingly.  (You can see the code starting on line [91 of MoppyPlayerOutput.java](https://github.com/SammyIAm/Moppy/blob/moppy-advanced/Java/MoppyDesk/src/moppydesk/outputs/MoppyPlayerOutput.java#L91-L102) )

There's no agreed-upon amount for the pitchbending, but I went with something that seemed pretty common (I can't remember it off the top of my head).

Moppy doesn't currently support the "Pitch Bend Sensitivity" messages though, and I might look into that someday.

**Comment by tg44** [comment]
Yeah its a same as my solution... Thx.
