### ISSUE TITLE
Is looping the midi possible

### ISSUE THREAD

**Issue by 446f6d** [samphonic/MoppyClassic#64]
Hi, I would like to know if it is possible to loop the midi file and get the floppy drive to play it on repeat continuously?

**Comment by MultiDaxio** [comment]
Hmmm... I think it is possible, but you need to mess up with moppy advanced
option, or just copy your midi file data (notes) to the end of the song
over and over to make it suuuper long.
- MultiDaxio

2014-04-19 17:37 GMT+02:00 446f6d notifications@github.com:

> Hi, I would like to know if it is possible to loop the midi file and get
> the floppy drive to play it on repeat continuously?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SammyIAm/Moppy/issues/64
> .

## 

Adam

**Comment by 446f6d** [comment]
Thanks for the advice MultiDaxio! I got it to loop by adding sequencer.setLoopCount(Sequencer.LOOP_CONTINUOUSLY); in Moppy Advanced! I am actually trying to use it as a device that plays background music only when someone is close enough.

**Comment by MultiDaxio** [comment]
No problem bro. Glad I have helped. May the Force be with you :)

2014-04-20 18:45 GMT+02:00 446f6d notifications@github.com:

> Thanks for the advice MultiDaxio! I got it to loop by adding
> sequencer.setLoopCount(Sequencer.LOOP_CONTINUOUSLY); in Moppy Advanced! I
> am actually trying to use it as a device that plays background music only
> when someone is close enough.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SammyIAm/Moppy/issues/64#issuecomment-40899058
> .

## 

Adam

**Comment by samphonic** [comment]
There's an option now in the latest commit that allows you to repeat the song after it's completed.  Though it sounds like you've found your own separate solution as well.  =)
