### ISSUE TITLE
Cannot load Moppy into NetBeans?

### ISSUE THREAD

**Issue by SoupMedic** [samphonic/MoppyClassic#67]
I'm new to this, and when I tried to load Moppy in NetBeans for the first time, it gave me a message saying there are "Project Problems" - one or more resources could not be found. When I click resolve problems, it tells me that  ["swing-app-framework" library could not be found (in MoppyDesk)]

Thanks for any insight you can provide!

**Comment by SoupMedic** [comment]
I guess I didn't pay attention, and I just had to click 'resolve' for it to install the plugin. Silly me.

**Comment by MultiDaxio** [comment]
Shortest issue on Sammy`s GitHub. Congratz! And now srsly, for any future problems just call Ghostbu... us :p
