### ISSUE TITLE
Drive not responding?

### ISSUE THREAD

**Issue by SoupMedic** [samphonic/MoppyClassic#68]
Hey guys, when I connect everything up and run the midi file, the drive is silent. I had a look at issue 62, and I will try to list the responses I would have to Sammy's questions.
- the midi file is an example one, so it DOES have playable notes
- The drive does not respond in any way to my pressing of the play/pause, or the stop/reset buttons.
- When I am playing a file (tetris theme :D) The RX light does blink 
- The arduino code did compile and upload successfully, I checked
-  When I manually tap the step/dir wires to their corresponding gnd wires, I get a sort of clicking/stuttering noise from the drive.
- The gnd pins for step and dir are both grounded to the arduino.

If you need more information, just ask!

Thanks!

**Comment by MultiDaxio** [comment]
Wires. Check dem wirez. I had a simmilar problem, simply swap pins of DIR
and STEP, or DIR and STEP with their corresponding GND pins. Wires are the
mosty tricky part to be honest.
 1 cze 2014 23:38 "Jamie MacFarland" notifications@github.com napisał(a):

**Comment by SoupMedic** [comment]
I tried swapping DIR and STEP, DIR/STEP and their GND pins, and different GND pins in every configuration I could think to try. Still nothing, but now only one of my GND pins makes the drive respond when tapped to the DIR/STEP pins, the one under STEP. No idea if that is significant.

**Comment by MultiDaxio** [comment]
Check Arduinos`sockets for pins, they might be damaged. If your STEP-GND
makes a signal, well that`s someting. Try replacing all your wires with new
ones. Then go to issue #62 and look for the link to the pin layout of
floppies (right-top corner, thanks Sammy).
2 cze 2014 12:12 "Jamie MacFarland" notifications@github.com napisał(a):

**Comment by samphonic** [comment]
First of all, thanks for that big list of answers, that really narrows down where the issue could be.  The blinking RX light means the software on the PC is functioning correctly, and you checked that the code made it to the Arduino, and when you tap the wires together you get stuttering which means your drive is at least functional.

I think @MultiDaxio 's spot on: it sounds like something to do with your wiring, though it sounds like you've tried a lot of various combinations.

A quick checklist (sounds like you've done this already though):
- GND pins from drive connected to GND on Arduino.  The ground pins on your drive will be the ones on the _keyed_ side of the floppy connector (i.e. the side with the little nub sticking out of it)
- The STEP pin should be connected to pin 2 on the Arduino, and the DIR pin to pin 3.  Alternately, try STEP to pin 4 and DIR to pin 5.

If it's convenient, if you can draw a diagram of how you've got things connected, or post a picture, that might help us guess at the issue.

**Comment by SoupMedic** [comment]
I checked the issue #62 and had a eureka moment. It turned out the row of pins that I thought was GND was actually the input pins, and vice versa. I don't know how I messed that up and didn't realize it, but THANK YOU for sticking with me and helping!

**Comment by samphonic** [comment]
Ah, there ya go.  You're not the first to mix those up.  =P  Glad it's working for you!

**Comment by SoupMedic** [comment]
Thanks for all the wonderful work you do, Sammy!

I am giggling like a tech in a computer store listening to this play Tetris!

**Comment by MultiDaxio** [comment]
_cough_ Deja vu _cough_. Anyways. Glad you made it pal! May the Force be
with You, Jamie :p
2 cze 2014 20:33 "Jamie MacFarland" notifications@github.com napisał(a):
