### ISSUE TITLE
Potential issue in loop over CommPortIdentifier's

### ISSUE THREAD

**Issue by MarcAndreWyss** [samphonic/MoppyClassic#69]
Hi all

I recently discovered Moppy and began to play with it. Thanks for the cool piece of software! Later I studied the code in the master branch and found a potential issue. At least it is a issue in my opinion even though it should not be a issue on most computers. The issue remains in the moppy-advanced branch as well.

The code loops over the CommPortIdentifier's, but it does not check the type of the communication port identifier. There are 5 potential types: I2C, PARALLEL, RAW, RS485 and SERIAL. If I'm not wrong the code would add all types and display them in the dropdown menu, which is definitely wrong in my opinion. Therefore I would change the code as follows:

---

In the master branch, file MoppyMainWindow.java, method updateComSelectionMenu():

Change the following:
Enumeration<CommPortIdentifier> e = CommPortIdentifier.getPortIdentifiers();
while (e.hasMoreElements()) {
    comSelectionMenu.addItem(e.nextElement().getName());
}

To:
Enumeration<CommPortIdentifier> e = CommPortIdentifier.getPortIdentifiers();
while (e.hasMoreElements()) {
    CommPortIdentifier comPortId = e.nextElement();
    if(comPortId.getPortType() == CommPortIdentifier.PORT_SERIAL){
        comSelectionMenu.addItem(comPortId.getName());
    }
}

---

In the moppy-advanced branch, file MoppyCOMBridge.java, method getAvailableCOMPorts():

Change the following:
Enumeration<CommPortIdentifier> comPorts = CommPortIdentifier.getPortIdentifiers();
while (comPorts.hasMoreElements()) {
    portIdentifierStrings.add(comPorts.nextElement().getName());
}

To:
Enumeration<CommPortIdentifier> comPorts = CommPortIdentifier.getPortIdentifiers();
while (comPorts.hasMoreElements()) {
    CommPortIdentifier comPortId = comPorts.nextElement();
    if(comPortId.getPortType() == CommPortIdentifier.PORT_SERIAL){
        portIdentifierStrings.add(comPortId.getName());
    }
}

---

What do you think?

Thanks,
Marc

**Comment by samphonic** [comment]
I'm not super familiar with how these designations affect the communication.  While it's probably true that Serial is going to be the most used option, I don't know whether or not the other options wouldn't possibly be used.  And since each operating system is rather different in serial stuff, I'd be a little concerned about which systems classify ports as what type of port.

It may bear more research, and if you want to write a pull request, I might look into it.  For now though, as long as people choose port that their Arduino is connected to, there shouldn't be any issues.

**Comment by MarcAndreWyss** [comment]
Unfortunately my old Lenovo laptop with a parallel port was damaged some weeks ago. Therefore I'm not able to test it. But it would surprise me if a parallel port would accept commands for serial ports. Even if they come through a Java wrapper library.

**Comment by samphonic** [comment]
Parallel and serial would be pretty different, I would think.  But i2c would be pretty similar I would think.

**Comment by MarcAndreWyss** [comment]
I guess we need then four new addon cards for our new testinfrastructure... :-D
