### ISSUE TITLE
Pinout Needed!!! Dell floppy drive with unusual cable.

### ISSUE THREAD

**Issue by sethhope** [samphonic/MoppyClassic#7]
Hello. My Dell floppy drive has an unusual cable and I dont know what the problem is. I thought I followed the pin numbers well, but it just doesnt work! Its the drive out of an old Dell optiplex GX280. I got 2 other drives to work but the third doesnt want to. Ill post a picture of the drive if needed. If you would like to email me, email me at support@jcamtech.com.
## Thanks!

Seth Hope
Programmer
Jcam Technologies
www.jcamtech.com

**Comment by samphonic** [comment]
Hi Seth,

Yeah, if you could post a picture that might help a fair bit with identifying the drive and pinout.  It very well could be a different interface than standard floppies.  Without a picture though, here's some steps you can use to try to manually identify the pins:
1. If it's anything like the standard floppy interface, all the pins along one side should be ground, and all the other pins should be at some higher voltage (5v I believe).  If you have a multimeter, try identifying which side is which.
2. Using a small piece of wire, connect pins on the floppy drive to other pins on the floppy drive (e.g. connect pin1 to pin2, then pin1 to pin3, 1-4,1-5, &c.)  If you know (from step 1) that one side is all ground, then you can just try connecting the ground pins to each of the non-ground pins (i.e. 1-2, 3-4, 5-6, &c.)
3. Eventually, one pair of pins should cause the LED on the front of the drive to light up.  You've located the drive-select pin!  If it's pin 12 or 14, try following the tutorial wiring again, it might still be a normal-interface, but with a different select-pin.
4. Finding the step pin may be difficult as it will by-default step backward, but some drives won't do anything if the head is all-the-way back already.  If you can carefully move the read-head into the center of its track and follow the same search procedure, when the head moves, you'll have the step pin.
5. The last pin will be the direction pin.  You can follow the same search pattern, but will need to ground the step-pin each time to see if the direction has changed.

Hopefully a picture will help me (or someone else on here) locate the proper pinout, but if not those steps should send you along that direction.  Just out of curiosity, do you know if it was a powered eject drive?  (i.e. can it automatically eject disks?)

**Comment by sethhope** [comment]
Thanks! I found out what the problem was. It was an unusual Dell digital connector... They were only used for a certain amount of time. They are always set to drive select A so some of the wires are reversed. There is no twist, as it it a hairthin ribbon cable. Thanks for the reply!!! My floppy drive set is working like a charm!

**Comment by samphonic** [comment]
Sweet!
