### ISSUE TITLE
Missing classpath items for swing-app-framework

### ISSUE THREAD

**Issue by baconwaifu** [samphonic/MoppyClassic#71]
My install of netbeans reports missing classpath items that are referenced but don't exist in the swing-app-framework library, I've tried redownloading, I've tried using ubuntu, mint, debian, windows, no luck

**Comment by samphonic** [comment]
You need to install the Swing Application Framework plugin for NetBeans.  It should be available in NetBean's plugins manager.

**Comment by samphonic** [comment]
There may be a potential loss of support for SAF in the near future of NetBeans though.  I'll keep #72 updated in that regard.
