### ISSUE TITLE
MoppyDesk give me a error and i don't understand 

### ISSUE THREAD

**Issue by MrBijnens** [samphonic/MoppyClassic#72]
I opened the file "MoppyDesk" in NetBeans but before I press the green button, give the project an error 
If I go, I see that in 'Source Packages' -> 'moppydesk' -> 'MoppyUI.java' is a problem called: 
import org.jdesktop.application.SingleFrameApplication; 

What should I do? 

ps: my English is not perfect, it is translated by "Google Translate"

**Comment by MultiDaxio** [comment]
Try redownloading the packgage containing Moppy advanced app. Then extract
it to one folder. Then, inside NetBeans try to go to that folder, look for
a weird looking, toolbox-like icon. Open it. Make sure that you do not move
the folder eith Moppy advanced app nowhere, when the app is running.
Hope I`ve helped :)

**Comment by MrBijnens** [comment]
Can you also happen to be so give me the link of a package? I was glad that I had found. Issue' new-button Sorry if I'm demanding surmountable.

**Comment by samphonic** [comment]
It sounds like you're missing the Swing Application Framework plugin for NetBeans.  You should be able to install it from the NetBeans plugins manager.

It sounds like there was at least some discussion of dropping support for SAF in the future of NetBeans.  I may need to convert Moppy to use its replacement if that happens.

**Comment by MrBijnens** [comment]
or mabey i should download the older version of NetBean, mabey the probleme wil be solved

**Comment by MultiDaxio** [comment]
Nah, it won`t hwlp, aa the newer version is addinv new thing to older. It
doesn`t change anything. You may try it though.

**Comment by MultiDaxio** [comment]
Also, Sammy, if that is the issue, I`d like to point out that you shouldn`t
update NetBeans... At least that`s ehat I do, and everything works just
fine...

**Comment by MrBijnens** [comment]
Success! It was indeed the application of single frame application that was not installed. 
Now I have the RxtxSerial update, and then hope of victory. Thank you very much

**Comment by MultiDaxio** [comment]
Glad it worked!

**Comment by MrBijnens** [comment]
but now, the next issue :-( : tis is what i get:
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path

i have the new version of RXTX-CommDrive in the MoppyDesk => lib placed but still th error

**Comment by MultiDaxio** [comment]
Are you sure you`ve placed it in a correct folder?

**Comment by MrBijnens** [comment]
I have put it here

![lib](https://cloud.githubusercontent.com/assets/8107110/3522283/ba9ffec4-074a-11e4-86d8-9d62c38324e5.png)

**Comment by MrBijnens** [comment]
these documents do I put here: Rxtx comm, Rxtx parallel and rxtx Serial

**Comment by samphonic** [comment]
You can try putting the RXTXcomm dll in your Java home folder, or preferably, edit the NetBeans Project's properties to pass the `-Djava.library.path` argument to java when running it.  it'll look something like `-Djava.library.path="C:\Folder\MoppyDesk\lib"`  (Google might help a little in explaining this more)

As for using older versions of NetBeans, it's certainly possible, but I would hate to require that everyone use an outdated version just to run Moppy.  Sounds like so far it's working okay, but if SAF has been deprecated, it would still be best of update it eventually.

**Comment by MrBijnens** [comment]
I posted the link here on Google and I came to issue # 2 of your channel. As solidsnake745 said, that's when I've succeeded. Thank you very much

**Comment by samphonic** [comment]
Hooray!  Glad you got it working.

**Comment by MrBijnens** [comment]
thank you also for the help and the instructables

**Comment by samphonic** [comment]
New builds no longer need the SAF or RXTX libraries.
