### ISSUE TITLE
This is an Extension Question:

### ISSUE THREAD

**Issue by MrBijnens** [samphonic/MoppyClassic#74]
In this movie (http://hackaday.com/2012/05/26/moppy-lets-you-play-your-floppy-drives/) you will see that he is a midi piano or used piano hacked. I also want to make something like that but I have no knowledge of JAVA, and do not know how to start it. Does anyone know where I can find the manual or the instructions I want to use this for my class 'teacher training' (I'm studying for Electrical and Informatics teacher, and within a few months I can to explain what an Arduino and how to get there a program insert),
but I want to use this for the interest in Electrical and Informatics

**Comment by samphonic** [comment]
If you're using the advanced branch of Moppy, then all you need to do is change the input mode to MIDI IN Port, and select the correct port for the MIDI keyboard you have hooked to your computer.  Getting the keyboard set up will be different for each keyboard, and is outside the scope of this particular project.

No additional knowledge of Java required.

**Comment by MrBijnens** [comment]
OK, Again thank you very much

**Comment by MrBijnens** [comment]
I have a MIDI keyboard (NanoKey 2) and bought this I tried one Moppy and this works. But if I do a second moppy or more moppy's, only works the first, the rest does nothing. (configuration: see picture)
Does this perhaps related to 'Enable Drive Pooling "and if so, can you explain to me what it is or give me a link to a website (if I ingeef in Google, I come to one of your issues out (these have I read and tried but nothing)
![naamloos](https://cloud.githubusercontent.com/assets/8107110/3618247/8b8c5a9e-0de7-11e4-84b6-8897dd7b155f.png)

**Comment by samphonic** [comment]
MIDI devices (like your keyboard) tend to only output data on a single channel.  So your keyboard is just outputting notes on channel 1, and therefore just gets played on the first floppy drive.

The good news is, the Drive-Pooling option was created for exactly this situation!  You'll want to change the numbers to say "Pool channels 1-1" "Into channels 1-[numberofdrives]".  And select a strategy like Round-Robin to make sure all the drives get used.

With Round-Robin pooling, each note on your keyboard will be played on the next available floppy drive as specified by the numbers in the "Into channels" section.

**Comment by MrBijnens** [comment]
I did that but the same problem still remains, The first moppy goes, but the second moppy does nothing

![naamloos](https://cloud.githubusercontent.com/assets/8107110/3618498/aab4018a-0dea-11e4-80a9-2570dced2871.png)

**Comment by samphonic** [comment]
You've got your pooling channels backward.  The first two boxes should both be 1.  The second two boxes should be 1-[number of drives].

(Thanks for the screenshots, by the way, that makes it WAY easier to help you)

**Comment by MrBijnens** [comment]
it works, Again, thank you very much, I'm not the smartest with this, but luckily you do. :)

**Comment by samphonic** [comment]
Hooray!
