### ISSUE TITLE
Problems with playing on more than 3 channels

### ISSUE THREAD

**Issue by sealj553** [samphonic/MoppyClassic#80]
Hello,
I have an Arduino UNO connected to 8 floppies and I can't get it to play anything on anything past the third drive, although I can occasionally get another working when I select drive pooling. Yes, I've tried switching drive and direction pins, and I've tried switching odd to even pins. Yes, I jumped the drive select pin. I have connected other floppies to the first three pins and they work fine. I used SpeedyMIDI and created an 8 channel midi file to test and it still doesn't play on any other channels. Most of the drives are still, but one of them clicks and on the other, the bottom motor spins (for spinning the disc). I am out of ideas on how to fix this. Thanks for your suggestions.

**Comment by samphonic** [comment]
Triple check your wiring on drives 4-8; it sounds wiring-related.  The bottom motor spinning on the drive indicates that either pin 10 or pin 16 has been grounded on that drive.  If it spins constantly, there could be some sort of fault or your drive select jumper is on the wrong pair.  If it only spins occasionally while music is playing, your direction or step wires are probably connected to the wrong pin on the drive.

Floppy drives can be weird with their wiring sometimes.  Maybe some of them have their pins upside down?  Try counting from the otherside perhaps.

**Comment by sealj553** [comment]
I rewired them and got it playing on 6 drives. I still have two that are wired the same, but don't respond. I will have to re-recheck the wiring on those. Thanks for the help!

**Comment by samphonic** [comment]
Do the activity/drive select lights come on on the two that aren't responding?  If not, you might try switching the drive-select to B (or to A, whichever it isn't now).  Most drives will do either, but some only seem to work if they're set to a specific drive letter.

**Comment by sealj553** [comment]
I have pins 13 and 14 bridged on all of them. On one of the drives, the drive select light stays on, no matter what. The motor on that one spins constantly, even if it's unplugged. On the other, the light is only on when the pins are bridged, like the others.
Now that I think of it, I think I might have shorted out one of my drives when testing my wiring...I did ruin my power supply, but I thought the drive was ok.

**Comment by samphonic** [comment]
The one with the light always on is probably not in good shape.  It could be that the other is just an unhappy drive as well; sounds like you've mostly got the wiring worked out now, so it may just be bad drives.
