### ISSUE TITLE
multi ardunio support

### ISSUE THREAD

**Issue by AAllport** [samphonic/MoppyClassic#81]
How do you do that?
I can see you can select multiple moppy output for midi Chanel's I's that how

**Comment by samphonic** [comment]
Once you have both Arduinos connected to your computer, just select the COM ports for each Arduino in the output area.

By default, the Arduino software only responds to channels 1-8, so for example, you could assign channels 1-4 to the COM port with one Arduino, and channels 5-8 to a different COM port with the other Arduino.  It's fairly trivial though to adjust the Arduino code to respond to channels 9-16 instead though, so ideally you could modify the code you upload to the second Arduino to respond to those channels.

**Comment by AAllport** [comment]
Then should I just be able to run moppydesk without changing anything

**Comment by AAllport** [comment]
``` wiring
currentPeriod[Serial.read()] = (Serial.read() << 8) | Serial.read();
```

do i just change the bit with the 8 or is it somewhere else?

**Comment by samphonic** [comment]
That's the right line, but that 8 needs to stay an 8 (it's bitshifting to make a two-byte integer)... it depends on exactly what you're trying to accomplish, but you should be able to just add a -16 on that line:
`currentPeriod[Serial.read()-16] = (Serial.read() << 8) | Serial.read();`

That will essentially treat messages destined for pin 18 (MIDI channel 9) as if they were destined for pin 2.

**Comment by AAllport** [comment]
very helpful @SammyIAm
