### ISSUE TITLE
Not really an issue, but more of a question (a few actually)

### ISSUE THREAD

**Issue by Schieggster** [samphonic/MoppyClassic#82]
First off, Thank you! This is more than entertaining for me.

Q1: Where do y'all get the midi files, and is there a specific source for low channel midi's?

Q2: Is it possible/ is there any way to condense midi channels into just a few? I'm probably only going to have about 6 total, and at 3 drives, I seem to miss a lot (I know I'll get the other notes as more drives come in, but I can hope).

Thanks!
Schieggster

**Comment by samphonic** [comment]
Sorry it's taken me a few days to get to this.  I usually find the MIDIs on Google, or I'll find a site that lists a whole bunch of them and browse through the list.  Generally they aren't already suitable for Moppy though, and need a little editing before they'll work right on the drives.

The drive pooling option at the bottom left of the MoppyDesk screen is what you're looking for to use more channels on fewer drives.  If you had 6 channels and 3 drives, you'd set the left numbers to 1-6 and the right ones to 1-3.  Basically this will assign any notes coming in on channels 1-6 to the next available drive between 1 and 3.  This means that sometimes if there are more than 3 notes playing simultaneously, one of the notes will get cut off by a new incoming note, but should let you hear the music relatively well.

**Comment by AAllport** [comment]
i allways wondered what drive pooling was
what is the stratagy for
