### ISSUE TITLE
Getting error on run time as java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver

### ISSUE THREAD

**Issue by sambsa** [samphonic/MoppyClassic#88]
I have windows 8.1, 64 bit system and I am using RXTX library:
I have done the following things as mentioned:
- Copied rxtxParallel.dll and rxtxSerial.dll inside C:\Program Files\Java\jdk1.8.0_25\jre\bin
- Copied RXTXcomm.jar inside C:\Program Files\Java\jdk1.8.0_25\jre\lib\ext

I am trying to execute the following program:
import gnu.io._;
import java.io._;
import java.util.*;

public class SimpleWrite implements Runnable, SerialPortEventListener {

```
public void run() {
}
static Enumeration portList;
static CommPortIdentifier portId;
static String messageString = "AAA";
static char ch = '"';
static String dest = ch + "XXXXXXXXXXX" + ch;  // 11 Digit Mobile Number.
static InputStream inputStream;
static SerialPort serialPort;
static OutputStream outputStream;
```

public void serialEvent(SerialPortEvent event) {
    switch (event.getEventType()) {
        case SerialPortEvent.BI:
        case SerialPortEvent.OE:
        case SerialPortEvent.FE:
        case SerialPortEvent.PE:
        case SerialPortEvent.CD:
        case SerialPortEvent.CTS:
        case SerialPortEvent.DSR:
        case SerialPortEvent.RI:
        case SerialPortEvent.OUTPUT_BUFFER_EMPTY:
            break;
        case SerialPortEvent.DATA_AVAILABLE: {

```
        BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
        String line = "";
        try {

            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }
        } catch (IOException e) {
            System.err.println("Error while reading Port " + e);
        }
        break;

    }
} //switch
```

}

public SimpleWrite(SerialPort serial) {
    try {
        inputStream = serial.getInputStream();
        try {
            serial.addEventListener(this);
        } catch (TooManyListenersException e) {
            System.out.println("Exception in Adding Listener" + e);
        }
        serial.notifyOnDataAvailable(true);

```
} catch (Exception ex) {
    System.out.println("Exception in getting InputStream" + ex);
}
```

}

public static void main(String[] args) {
    String line1 = "AT+CSMS=1\r\n";
    String line2 = "AT+CMGS=" + dest + "\r\n";
    String line3 = messageString + "\r\n";

```
portList = CommPortIdentifier.getPortIdentifiers();

while (portList.hasMoreElements()) {
    portId = (CommPortIdentifier) portList.nextElement();
    if (portId.getPortType() == CommPortIdentifier.PORT_SERIAL) {
        if (portId.getName().equals("COM3")) {
            System.out.println("SMS Sending....Port Found");
            try {
                serialPort = (SerialPort) portId.open("SimpleWriteApp", 2000);
                SimpleWrite wr = new SimpleWrite(serialPort);

            } catch (PortInUseException e) {
                System.out.println("Port In Use " + e);
            }
            try {
                outputStream = serialPort.getOutputStream();
            } catch (IOException e) {
                System.out.println("Error writing to output stream " + e);
            }
            try {
                serialPort.setSerialPortParams(9600, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            } catch (UnsupportedCommOperationException e) {
            }
            try {
                outputStream.write(line1.getBytes());
                outputStream.write(line1.getBytes());
                outputStream.write(line2.getBytes());
                outputStream.write(line3.getBytes());
                outputStream.write(26);
                outputStream.flush();
            } catch (Exception e) {
                System.out.println("Error writing message " + e);
            }
        }
    }
}
```

}

/**
- show text in the text window
  *
- @param Text text string to show on the display
  */
  public static void showText(String Text) {
  System.out.println(Text);
  }
  }

I am getting the error as follows:

C:>javac SimpleWrite.java

C:>java SimpleWrite 
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while
loading gnu.io.RXTXCommDriver
Exception in thread "Thread-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in
java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
        at SerialConnection.openConnection(SerialConnection.java:71)
        at Sender.send(Sender.java:46)
        at SMSClient.run(SMSClient.java:39)
        at java.lang.Thread.run(Unknown Source)

Please guide me guys to solve this problem. I am stuck for 2 days with this problem. Help will be appreciated. Thanks!!

**Comment by samphonic** [comment]
@MoppyDoppy has responded to your post in the other thread with help for this issue.  Generally though, this is a forum for Moppy-related questions; you might be better off using Google or asking on the site where you downloaded rxtx for questions not related to Moppy.
