### ISSUE TITLE
Lost MIDI In Port functionality due to addition of filterControls

### ISSUE THREAD

**Issue by solidsnake745** [samphonic/MoppyClassic#95]
Looks like with the addition of filter controls we lost the functionality of MIDI In. I'd explain more and stuff, but just had eye surgery and can barely see/stare at a white screen. I trust you'll figure this out on your own. Fix is in MoppyControlWindo, line 231. Change seqControls to currentInputPanel. That way whatever the current panel is, the receiver is set properly to filter controls. Please review, I made the quickest change I thought would fix the problem without analyzing it's impact.
![untitled](https://cloud.githubusercontent.com/assets/1118404/6548832/682a2d8a-c5dc-11e4-9478-d15620b12758.png)

**Comment by samphonic** [comment]
I'll try to take a look at this as soon as I can.  (I did fail to check MIDI In after those changes though, so that's my bad)

**Comment by samphonic** [comment]
Sorry it took so long to get to this; busy times.  Your fix was exactly the solution.  Hope your eye's recovered well.
